import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    loans: "My Loans",
    simulation: "Simulation",
    analysis: "Stress Analysis",
    fraudCheck: "Fraud Check",
    emergencyFund: "Emergency Fund",
    familyFinance: "Family Finance",
    voiceTrack: "Voice Track",
    myGoals: "My Goals",
    adminPanel: "Admin Panel",
    aiInsights: "AI Insights",
    logout: "Logout",

    // Dashboard
    hello: "Hello",
    welcomeJohn: "Welcome, John 👋",
    welcomeUser: "Welcome, {name} 👋",
    premiumAccount: "Premium Account",
    dashboardDesc: "Analyze salary deductions, configure itemized tracking, check DTI metrics, and view real-time summaries.",
    configureFinancials: "Configure Financials",
    injectDemo: "Inject Demo Dataset",
    monthlyIncome: "Monthly Income",
    expenses: "Expenses",
    totalEMI: "Total Active EMIs",
    managedOutflow: "Managed outflow",
    debtCommitments: "Debt Commitments",
    financesBreakdown: "Finances Breakdown",
    allocationMapping: "Allocation mapping of income commitments",
    activePortfolio: "Active Portfolio",
    portfolioDesc: "Comprehensive audit of active loan streams",
    manageLoans: "Manage Loans",
    loanDetails: "Loan Details",
    amount: "Amount",
    rate: "Rate",
    status: "Status",
    financialHealth: "Financial Health Score",
    healthStatusExcellent: "Excellent Standing",
    healthStatusModerate: "Moderate Health",
    healthStatusRisk: "Risk Profile Detected",
    healthDesc: "Your savings coverage is robust against active EMIs.",
    trajectory: "Debt-Stress Trajectory",
    retryConnection: "Retry Connection",
    reauthenticate: "Re-authenticate (Logout & Login)",
    failedSync: "Failed to Sync Dashboard",
    hideSummary: "Hide Summary",
    inAppSummary: "In-App Financial Summary",
    confidentialAudit: "Confidential Audit",
    deductionsSummary: "Deductions Summary",
    grossSalaryLabel: "Gross Salary:",
    pfLabel: "Provident Fund (PF):",
    ptLabel: "Professional Tax:",
    itLabel: "Income Tax:",
    netTakeHomeLabel: "Net Take-Home:",
    expenseAllocations: "Expense Allocations",
    coreTotal: "Core Total:",
    surplusHeadroom: "Surplus Headroom:",
    dtiRatioLabel: "DTI Ratio:",
    savingsRateLabel: "Savings Rate:",
    advisorRec: "Advisor Recommendations",
    savingsCatStatus: "Savings Category Status:",
    combinedRiskFactor: "Combined Risk Factor:",
    dtiTip: "Keep DTI ratio below 30% to shield from cash-crunch stresses.",
    howToUseTitle: "How To Use Smart Loan Analyzer",
    howToUseDesc: "Welcome to the platform. Explore the onboarding workflow using our realistic guide profile, John (28 years old, Salaried Employee). Click the walkthrough button above to view the journey!",
    step1Title: "Step 1: Register/Login",
    step1Desc: "Sign up or enter credentials to start. Example demo profile: Email john@example.com / Pass John123.",
    step2Title: "Step 2: Salary Configuration",
    step2Desc: "Enter Gross Salary (₹60,000). The engine auto-computes a 12% PF (₹7,200), subtracting Professional Tax (₹200) and Income Tax (₹2,000) for a Net Take-home of ₹50,600.",
    step3Title: "Step 3: Expense Tracking",
    step3Desc: "Log core outlays: Rent (₹15k), Food (₹6k), Transport (₹2k), Electricity (₹1.5k), Internet (₹800), Insurance (₹2k), and Others (₹3k) to evaluate your total monthly expenditures of ₹30,300.",
    step4Title: "Step 4: Disposable Surplus",
    step4Desc: "Net Salary (₹50,600) minus Expenses (₹30,300) leaves a disposable cushion of ₹20,300. This buffer decides your safe borrowing thresholds.",
    guidedJourneyTitle: "Interactive Guided Journey",
    guidedJourneyDesc: "We have constructed a full walkthrough mapping page displaying maps, features details, and simulations. Navigate directly to explore all elements.",
    startWalkthroughBtn: "Start Walkthrough 🚀",
    leafletLandmarks: "Walkthrough Steps:",
    leafletLandmarksDesc: "• Account setup & Salary metrics • Cost items logs & surplus tracking • Simulation calculations & Health checks",
    netSalaryCardTitle: "Net Take-Home Salary",
    afterDeductions: "After PF & tax deductions",
    totalMonthlyExpensesTitle: "Total Monthly Expenses",
    coreOutflowsTracked: "Core outflows tracked",
    disposableBufferTitle: "Disposable Buffer",
    freeCashSurplus: "Free cash surplus",
    monthlyActiveEmisTitle: "Monthly Active EMIs",
    financesAllocProfile: "Finances Allocation Profile",
    financesAllocProfileDesc: "Ratio comparison of income, expenses, and loan liabilities.",
    expensesDistTitle: "Expenses Distribution",
    expensesDistDesc: "Categories breakdown of core expenditures.",
    noExpensesConfigured: "No expenses configured yet",
    derivedHealthScore: "Derived dynamically based on savings capability, total expense constraints, and debt liabilities ratios.",
    healthRatingLabel: "Health Rating",
    computeLoanAffordability: "Compute Loan Affordability",
    calcMonthlyEmi: "Calculated Monthly EMI",
    totalInterestPaid: "Total Interest Paid:",
    totalCumRepayment: "Total Cumulative Repayment:",
    affordabilityAnalysisTitle: "Affordability Analysis",
    highlyAffordable: "Highly Affordable ✅",
    emiDispPercentage: "EMI is {percent}% of your disposable income.",
    riskyLeverage: "Risky Leverage ⚠️",
    emiRiskyPercentage: "EMI takes {percent}% of disposable funds. Proceed cautiously.",
    notAffordable: "Not Affordable ❌",
    emiNotAffordablePercentage: "EMI exceeds 50% ({percent}%) of remaining cash. Recommended to reject.",
    configFinancialProfile: "Configure Financial Profile",
    specifyIncomeExpenses: "Specify detailed income components and itemized expenses tracking.",
    salaryModuleStructure: "Salary Module Structure",
    grossSalaryInput: "Gross Salary",
    pfRateInput: "PF Rate (%)",
    ptInputLabel: "Prof. Tax (PT)",
    itInputLabel: "Income Tax (IT)",
    itemizedExpensesTracking: "Itemized Expenses Tracking",
    monthlyRentInput: "Monthly Rent",
    foodGroceriesInput: "Food & Groceries",
    transportInputLabel: "Transportation",
    electricityInputLabel: "Electricity",
    internetInputLabel: "Internet / Wifi",
    insuranceInputLabel: "Insurance",
    otherExpensesInputLabel: "Other Spends",
    savingFinancials: "Saving...",
    saveFinancialsBtn: "Save Financial Details",

    // Goals
    goalsTitle: "Emotional Money Timeline",
    goalsDesc: "Define savings goals and simulate purchase dates against unpruned flexible expenditures.",
    createGoal: "Create Target Goal",
    goalIdentifier: "Goal Identifier",
    targetCost: "Target Cost ($)",
    monthlyContribution: "Monthly Contribution",
    addTargetGoal: "Add Target Goal",
    forecastOnline: "Forecast Timelines",

    // Fraud
    fraudTitle: "AI Transaction Guard",
    fraudDesc: "Evaluate and audit high-risk merchant payments before confirming settlements.",
    analyzePayment: "Analyze Payment Criteria",
    settlementAmount: "Settlement Amount ($)",
    category: "Category",
    merchant: "Receiving Merchant",
    merchantLoc: "Merchant Location",
    analyzeSettlement: "Analyze Settlement",
    neuralEngine: "Neural Engine Active",

    // Family Finance
    familyTitle: "Family Financial Ecosystem",
    familyDesc: "Link accounts to coordinate shared wallets, family limits, elder alerts, and group saving plans.",
    groupManagement: "Group Management",
    establishGroup: "Establish Group",
    establishGroupDesc: "Initialize a secure shared financial workspace and issue invite linkages instantly.",
    createNewEcosystem: "Create New Ecosystem",
    ecosystemConnectionId: "Ecosystem Connection ID",
    provideConnectionIdDesc: "Provide an active family token ID to download shared wallet indexes.",
    synchronizeGroup: "Synchronize Group",
    synching: "Synching...",
    inviteCode: "Invite Code: ",
    shareCodeWithFamily: "Share Code With Family",
    sharedBalance: "Shared Balance",
    topUp: "+ Top Up",
    amountVal: "Amt ($)",
    primaryPool: "Primary Pool",
    activeWallet: "Active Wallet",
    ecosystemMembers: "Ecosystem Members",
    connected: "Connected",
    recentTransactions: "Recent Family Pool Transactions",
    liveLedger: "Live ledger",
    member: "Member",
    reason: "Reason",
    date: "Date",
    noTransactions: "No transactions recorded yet.",
    addMember: "Add Family Member",
    inviteMemberDesc: "Invite existing members using their email to coordinate limits and elder expenses.",
    emailAddress: "Email Address",
    nickname: "Nickname",
    role: "Role",
    monthlyLimit: "Monthly Limit ($)",
    parent: "Parent",
    child: "Child",
    elder: "Elder",
    sendingInvite: "Inviting...",
    inviteSuccess: "Successfully added family member!",

    // Emergency Fund
    fundTitle: "Emergency Shared Wallet & Fund",
    fundDesc: "Keep your critical funds reserved. Track runway estimation and contribute monthly to avoid debt stress.",
    fundBalance: "Fund Balance",
    monthsOfRunway: "Months of Runway",
    runwayDesc: "Estimated months of survival based on current balance and expenses.",
    fundGoal: "Fund Target",
    monthlyContributionGraph: "Monthly Contribution Progress",
    contribute: "Contribute to Fund",
    withdraw: "Emergency Withdrawal",

    // Simulation
    simTitle: "What-If Interest Rate Simulator",
    simDesc: "Simulate structural adjustments like principal changes, interest changes, or prepayments.",
    loanDetailsForm: "Loan Parameters",
    simulateButton: "Run Structural Simulation",
    simResults: "Simulation Insights & Metrics",

    // Stress Analysis
    stressTitle: "Debt Stress & Vulnerability Audit",
    stressDesc: "Analyze how vulnerable your cash flow is under various financial shocks.",
    runStressCheck: "Run Vulnerability Scan",

    // Voice Tracker
    voiceTitle: "Voice Debt Assistant",
    voiceDesc: "Command your loan manager with natural voice sentences. Real-time NLP parsing extracts actionable events.",
    speakCommand: "Tap to Speak Command",
    listening: "Listening...",

    // General UI
    save: "Save",
    cancel: "Cancel",
    loadingVal: "Loading...",
    backToDashboard: "Back to Dashboard",
    inviteCodeRequired: "Group ID is required to sync",

    // Loans
    manageLoansLocally: "Manage your loans locally. Simulation uses backend /api/loan/simulate.",
    addNewLoan: "Add New Loan",
    loanType: "Loan Type",
    loanTypePlaceholder: "e.g., Home Loan",
    amountPlaceholder: "150000",
    interestPlaceholder: "3.5",
    durationPlaceholder: "240",
    adding: "Adding...",
    addLoanButton: "Add Loan",
    yourLoans: "Your Loans",
    noLoans: "No loans added yet.",
    amountLabel: "Amount",
    interestLabel: "Interest",
    durationLabel: "Duration",
    statusLabel: "Status",

    // Simulation Additional
    simSandbox: "Interactive Sandbox",
    simMainTitle: "Financial Scenario Simulator",
    simDescExtended: "Model prepayments, EMI adjustments, and refinance rates to unlock compounding interest savings.",
    scenarioParams: "Scenario Parameters",
    scenarioDesc: "Adjust inputs or use the precision sliders to test payoff schedules.",
    loanPrincipal: "Loan Principal ($)",
    tenureHorizon: "Tenure Horizon (Months)",
    tenure1Year: "1 Year (12m)",
    tenure15Years: "15 Years (180m)",
    tenure30Years: "30 Years (360m)",
    payoffBoosters: "What-If Payoff Boosters",
    extraMonthlyPayoff: "Extra Monthly Payoff ($)",
    oneTimePrepayment: "One-Time Prepayment ($)",
    simCompounding: "Simulating Repayment Compounding...",
    runSandbox: "Run Simulation Sandbox",
    calcException: "Calculation Exception",
    waitingScenario: "Waiting for Repayment Scenario",
    waitingScenarioDesc: "Select your simulation metrics and click 'Run Simulation' to model custom prepayment and interest amortization impacts.",
    interestSavings: "Interest Savings",
    interestSavingsDesc: "See how prepaying early eliminates thousands in compound interest.",
    timelineShortening: "Timeline Shortening",
    timelineShorteningDesc: "Model custom monthly buffers and track your new debt-free milestone date.",
    compoundingBenefit: "Compounding Benefit",
    repaymentSummary: "Repayment Summary",
    highOptimization: "High Optimization",
    projectedInterestSaved: "Projected Interest Saved",
    interestSavedDesc: "This is the total money that will stay in your wallet instead of going to interest charges.",
    newMonthlyEmi: "New Monthly EMI",
    remainingHorizon: "Remaining Payoff Horizon",
    optimizedDate: "Optimized Debt-Free Date",
    payoffComparison: "Payoff Amortization Comparison",
    originalHorizon: "Original Horizon",
    optimizedHorizon: "Optimized Horizon",
    quicker: "quicker!",
    aiScenarioCounsel: "AI Scenario Counsel",
    synthesizingData: "Synthesizing data...",
    retriggerAI: "Re-trigger AI Analysis",

    // Stress Analysis Additional
    coreRiskDiagnostic: "Core Risk Diagnostic",
    debtStressAnalysisTitle: "Debt Stress Analysis",
    debtStressDescExtended: "Understand how heavily your monthly amortization commitments stress your active disposable cashflow.",
    incomeMinusExpenses: "Income minus fixed expenses",
    activeLoanPayments: "Sum of all active loan payments",
    disposableCashflow: "Disposable Cashflow",
    totalMonthlyEmi: "Total Monthly EMI",
    combinedStressScore: "Combined Stress Score",
    debtToDisposableRatio: "Debt-to-disposable ratio",
    historicalTrend: "Historical Risk Amortization Trend",
    timelineTrackStress: "Timeline track of your debt stress score index.",
    stressContribution: "Stress Contribution by Individual Loan",
    isolatedImpactScore: "Isolated impact score of each active loan item on your cashflow.",
    activeObligation: "Active Obligation",
    stressRatio: "stress ratio",
    noLoansDetected: "No Loans Detected",
    noLoansDetectedDesc: "Add amortized loan liabilities on the Loan Ledger page to review stress audits.",
    primaryStressDriver: "Primary Stress Driver",
    contributesLargest: "contributes the single largest cashflow pressure point",
    ratioText: "individual ratio.",
    debtDisposableRatioText: "Debt-to-Disposable Cashflow Ratio:",
    consumeDisposable: "Your amortized EMIs consume",
    safeCashflowRunway: "Safe Cashflow Runway:",
    preserveMonthlyNet: "You preserve a monthly net cash balance of",
    discretionarySavings: "for savings and discretionary activities.",
    cashflowAlert: "Cashflow Alert",
    stressExceedsWarning: "Your debt stress ratio exceeds the highly recommended 35% safe threshold. Prepayment modeling or loan refinancing is highly advised to prevent savings attrition.",

    // Walkthrough content
    w_welcome_title: "👋 Welcome John!",
    w_welcome_subtitle: "Meet your guide companion",
    w_welcome_desc: "Hi, I am John. Let me show you how Smart Loan Analyzer helps me manage my money.",
    w_welcome_label: "Profile Summary",
    w_welcome_body: "Age: 28 years old \nProfession: Salaried employee \nGoal: Save money, avoid cash-crunch stress, and plan for a bike loan.",
    w_welcome_footer: "🎯 Journey objective: Keep cash reserves healthy",

    w_account_title: "👤 Setup Account",
    w_account_subtitle: "First Step to Financial Safety",
    w_account_desc: "First create your account so the app knows who you are.",
    w_account_label: "Registration",
    w_account_footer: "Verified Demo Profile Details",

    w_salary_title: "💰 Salary Section",
    w_salary_subtitle: "Gross Salary vs Net Take-Home",
    w_salary_desc: "John reaches Salary Section 💰. I first add my monthly salary.",
    w_salary_label: "Salary Breakdown",

    w_expense_title: "🏠 Expense Section",
    w_expense_subtitle: "Keep track of where cash flies",
    w_expense_desc: "John moves to Expense Section 🏠. I track where my money goes every month.",
    w_expense_label: "Floating Expense Items",

    w_savings_title: "📊 Understand Savings",
    w_savings_subtitle: "Remaining Cash Surplus",
    w_savings_desc: "John moves to Savings Section 📊. This tells me how much money I can save.",
    w_savings_label: "Savings Cushion",

    w_loan_title: "🏦 Check Loan Calculator",
    w_loan_subtitle: "Simulate and Test EMI",
    w_loan_desc: "John reaches Loan Calculator 🏦. I check if I can afford a loan before taking it.",
    w_loan_label: "Bike Loan Simulation",

    w_stress_title: "⚠️ Debt Stress Analysis",
    w_stress_subtitle: "How much of your salary goes to loans",
    w_stress_desc: "John reaches Debt Stress Analysis ⚠️. The app tells me if my loans are safe or risky.",
    w_stress_label: "Stress Meter",

    w_fund_title: "🛟 Emergency Fund",
    w_fund_subtitle: "Preparing for unexpected costs",
    w_fund_desc: "John reaches Emergency Fund 🛟. I prepare money for emergencies.",
    w_fund_label: "Safety Runway",

    w_goals_title: "🎯 Financial Goals",
    w_goals_subtitle: "Planning Future Dreams",
    w_goals_desc: "John reaches Financial Goals 🎯. I plan my future goals.",
    w_goals_label: "Future Goals",

    w_ai_title: "🤖 AI Assistant",
    w_ai_subtitle: "Your Money Assistant Friend",
    w_ai_desc: "John meets AI Assistant 🤖. I can ask financial questions and get guidance.",
    w_ai_label: "AI Guidance",

    w_dashboard_title: "📈 Dashboard",
    w_dashboard_subtitle: "Visual overview of cash stability",
    w_dashboard_desc: "John reaches Dashboard 📈. Now I can see my complete financial health.",
    w_dashboard_label: "Health Status",

    w_prev: "Previous",
    w_next: "Next Step",
    w_finish: "Enter Dashboard",
    w_skip: "Skip Tour",
    ef_builder_title: "Emergency Fund Builder",
    ef_builder_desc: "Build a 6-month safety net — auto-calculated from your expenses.",
    ef_setup_financials: "Setup Financials",
    ef_transactions: "Transactions",
    ef_add_money: "Add Money",
    ef_withdraw: "Withdraw",
    ef_current_balance: "Current Balance",
    ef_target_6m: "Target (6 months)",
    ef_monthly_expenses: "Monthly Expenses",
    ef_total_accumulated: "Total Accumulated",
    ef_progress: "Progress",
    ef_saved: "saved",
    ef_complete: "Complete",
    ef_growth_trend: "Savings Growth Trend",
    ef_auto_saving_mode: "Auto-Saving Mode",
    ef_auto_saving_desc: "Per-transaction round-up amount added to your fund.",
    ef_support_runway: "Support Runway",
    ef_runway_desc_detail: "How many months your fund covers at current expenses.",
    ef_months: "months",
    ef_fully_protected: "Fully Protected",
    ef_partial_coverage: "Partial Coverage",
    ef_low_build_now: "Low — Build Now",
    ef_based_on_expenses: "Based on expenses",
    ef_health: "Fund Health",
    ef_remaining_to_goal: "Remaining to Goal",
    ef_autosave_per_txn: "Auto-Save per Txn",
    ef_add_money_modal_desc: "Manually contribute to your emergency fund.",
    ef_amount_inr: "Amount (₹)",
    ef_note_optional: "Note (optional)",
    ef_note_placeholder: "e.g. Bonus deposit",
    ef_deposit_btn: "Deposit",
    ef_processing: "Processing...",
    ef_withdraw_warning: "Only withdraw for genuine emergencies.",
    ef_reason_required: "Reason *",
    ef_reason_placeholder: "e.g. Medical emergency",
    ef_withdraw_btn: "Withdraw",
    ef_financial_setup_title: "Financial Setup",
    ef_target_formula: "Your target = Monthly Expenses × 6 months.",
    ef_monthly_income_label: "Monthly Income (₹)",
    ef_monthly_expenses_label: "Monthly Expenses (₹) *",
    ef_current_savings_label: "Current Savings / Initial Balance (₹)",
    ef_calculated_target: "Calculated Target",
    ef_saving: "Saving...",
    ef_save_setup_btn: "Save Financial Setup",
    ef_txn_history_title: "Transaction History",
    ef_no_txns: "No transactions yet. Add money to get started.",
    ef_profile_not_set: "Financial profile not set",
    ef_profile_not_set_desc: "Click Setup Financials to enter your monthly income & expenses. Your 6-month target will be calculated automatically.",
    w_calculated_as: "Calculated as",
    w_months_plural: "Months",
    w_optimize_spends: "Optimize spends?",
    w_dashboard_footer_msg: "Successfully completed Walkthrough!",
    w_net: "Net",
    w_cost: "Cost",
    o_loan_num: "Loan #",
    o_click_add_loan: "Click Add Loan to enter existing EMIs",
    g_target: "Target",
    g_saved: "Saved",
    g_monthly: "Monthly",
    g_remaining: "Remaining",
    g_progress: "Progress",
    travel: "Travel",
    gadget: "Gadget",
    health: "Health"    ,
    g_builder_title: "My Goals",
    g_builder_desc: "Set savings goals, track progress, and hit every milestone.",
    g_new_goal: "New Goal",
    g_total_goals: "Total Goals",
    g_active: "Active",
    g_completed: "Completed",
    g_no_goals: "No goals yet",
    g_no_goals_desc: "Create your first savings goal to get started.",
    g_create_first: "+ Create First Goal",
    g_completed_goals: "Completed Goals",
    g_edit: "Edit",
    g_complete: "Complete",
    g_delete: "Delete",
    g_icon: "Icon",
    g_goal_name: "Goal Name *",
    g_target_amount: "Target Amount (₹) *",
    g_monthly_contribution: "Monthly Contribution (₹) *",
    g_already_saved: "Already Saved (₹)",
    g_category: "Category",
    g_target_date: "Target Date (optional)",
    g_edit_goal: "Edit Goal",
    g_create_goal: "Create New Goal",
    g_saving: "Saving...",
    g_save_changes: "Save Changes",
    g_create_goal_btn: "Create Goal",
    g_est_completion: "Est. completion",
    g_month_singular: "month",
    g_months_plural: "months",
    g_name_required: "Goal name is required.",
    g_target_gt_0: "Target amount must be greater than 0.",
    g_contribution_gt_0: "Monthly contribution must be greater than 0.",
    g_delete_confirm: "Delete this goal? This cannot be undone.",
    g_toast_deleted: "🗑️ Goal deleted.",
    g_toast_failed_delete: "Failed to delete goal.",
    g_toast_completed: "🎉 Goal marked as complete!",
    g_toast_failed_complete: "Failed to mark complete.",
    o_personal_finance: "Personal Finance",
    o_loan_details: "Loan Details",
    o_review_confirm: "Review & Confirm",
    o_set_profile: "Set Up Your Financial Profile",
    o_profile_desc: "This takes 2 minutes. Your data drives accurate stress scores.",
    o_income_expenses: "Income, expenses & savings",
    o_existing_loans_opt: "Existing loans (optional)",
    o_verify_info: "Verify your information",
    o_monthly_cash_flow: "Your monthly cash flow details",
    o_monthly_income: "Monthly Income *",
    o_monthly_expenses: "Monthly Expenses *",
    o_total_savings: "Total Savings",
    o_emergency_fund: "Emergency Fund",
    o_occupation: "Occupation",
    o_select_occupation_opt: "Select occupation (optional)",
    o_live_preview: "Live Preview",
    o_disposable: "Disposable",
    o_existing_loans: "Existing Loans",
    o_optional_skip: "Optional — skip if you have no loans",
    o_add_loan: "Add Loan",
    o_no_loans_yet: "No loans added yet",
    o_add_first_loan: "+ Add First Loan",
    o_loan_type: "Loan Type",
    o_loan_amount_label: "Loan Amount (₹)",
    o_interest_rate_label: "Interest Rate (%)",
    o_emi_amount_label: "EMI Amount (₹)",
    o_tenure_months_label: "Tenure (Months)",
    o_estimated_dti: "Estimated DTI",
    o_everything_looks_good: "Everything looks good?",
    o_financial_overview: "Financial Overview",
    o_disposable_income: "Disposable Income",
    o_dti_ratio: "Your Debt-to-Income Ratio",
    o_back: "Back",
    o_next: "Next",
    o_complete_setup: "Complete Setup",
    o_income_gt_0: "Monthly income must be greater than ₹0",
    o_expenses_ge_0: "Expenses must be 0 or more",
    o_savings_ge_0: "Savings must be 0 or more",
    o_saving_loading: "Saving...",
    o_occupation_salaried: "Salaried Employee",
    o_occupation_self: "Self-Employed / Freelancer",
    o_occupation_business: "Business Owner",
    o_occupation_govt: "Government Employee",
    o_occupation_student: "Student",
    o_occupation_retired: "Retired",
    o_occupation_other: "Other",
    o_loan_personal: "Personal Loan",
    o_loan_home: "Home Loan",
    o_loan_car: "Car Loan",
    o_loan_edu: "Education Loan",
    o_loan_biz: "Business Loan",
    o_loan_cc: "Credit Card",
    o_loan_other: "Other",
    // New keys
    notifications: "Notifications",
    new: "new",
    clearAll: "Clear All",
    allCaughtUp: "All caught up! 🎉",
    askAiAssistant: "Ask AI Assistant",
    selectLanguage: "Select Language",
    aiInsightsPanel: "AI Insights Panel",
    currentBalance: "Current Balance",
    neuralEngineActive: "Neural Engine Active",
    aiAdvisorySuggestions: "Based on financial parameters, we recommend optimizing discretionary spends.",
    calibrateMicroSavings: "Setup saving limits to simulate different stress scenarios.",
    ef_deposit_success: "Deposit successful!",
    ef_deposit_failed: "Deposit failed. Try again.",
    ef_withdraw_success: "Withdrawal successful!",
    ef_withdraw_failed: "Withdrawal failed. Try again.",
    ef_setup_saved: "Financial setup saved!",
    ef_setup_failed: "Setup failed. Try again.",
    ef_balance_label: "Balance",
    ef_mode_gentle: "Gentle Mode",
    ef_mode_moderate: "Moderate Mode",
    ef_mode_aggressive: "Aggressive Mode",
    ef_per_txn: "/txn",
    retry: "Retry",
    g_cat_other: "🎯 Other",
    g_cat_vehicle: "🚗 Vehicle",
    g_cat_travel: "✈️ Travel",
    g_cat_gadget: "💻 Gadget",
    g_cat_education: "🎓 Education",
    g_cat_home: "🏠 Home",
    g_cat_health: "❤️ Health",
    g_cat_emergency: "🛡️ Emergency" 
  },
  kn: {
    // Navigation
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌",
    loans: "ನನ್ನ ಸಾಲಗಳು",
    simulation: "ಸಿಮ್ಯುಲೇಶನ್",
    analysis: "ಒತ್ತಡದ ವಿಶ್ಲೇಷಣೆ",
    fraudCheck: "ವಂಚನೆ ಪರಿಶೀಲನೆ",
    emergencyFund: "ತುರ್ತು ನಿಧಿ",
    familyFinance: "ಕುಟುಂಬ ಹಣಕಾಸು",
    voiceTrack: "ಧ್ವನಿ ಟ್ರ್ಯಾಕ್",
    myGoals: "ನನ್ನ ಗುರಿಗಳು",
    adminPanel: "ಅಡ್ಮಿನ್ ಪ್ಯಾನಲ್",
    aiInsights: "ಎಐ ಒಳನೋಟಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",

    // Dashboard
    hello: "ನಮಸ್ಕಾರ",
    welcomeJohn: "ಸ್ವಾಗತ, ಜಾನ್ 👋",
    welcomeUser: "ಸ್ವಾಗತ, {name} 👋",
    premiumAccount: "ಪ್ರೀಮಿಯಂ ಖಾತೆ",
    dashboardDesc: "ಸಂಬಳದ ಕಡಿತಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ, ವೆಚ್ಚಗಳನ್ನು ಸಂರಚಿಸಿ, ಡಿಟಿಐ ಸೂಚಕಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಹಣಕಾಸು ವರದಿ ವೀಕ್ಷಿಸಿ.",
    configureFinancials: "ಹಣಕಾಸು ಸಂರಚಿಸಿ",
    injectDemo: "ಡೆಮೊ ಡೇಟಾ ಸೇರಿಸಿ",
    monthlyIncome: "ಮಾಸಿಕ ಆದಾಯ",
    expenses: "ವೆಚ್ಚಗಳು",
    totalEMI: "ಒಟ್ಟು ಸಕ್ರಿಯ ಇಎಂಐಗಳು",
    managedOutflow: "ನಿರ್ವಹಿಸಿದ ಹೊರಹರಿವು",
    debtCommitments: "ಸಾಲದ ಬದ್ಧತೆಗಳು",
    financesBreakdown: "ಹಣಕಾಸು ವಿಭಜನೆ",
    allocationMapping: "ಆದಾಯ ಬದ್ಧತೆಗಳ ಹಂಚಿಕೆ ಮ್ಯಾಪಿಂಗ್",
    activePortfolio: "ಸಕ್ರಿಯ ಸಾಲಗಳು",
    portfolioDesc: "ಸಕ್ರಿಯ ಸಾಲದ ಸ್ಟ್ರೀಮ್‌ಗಳ ಸಮಗ್ರ ಲೆಕ್ಕಪರಿಶೋಧನೆ",
    manageLoans: "ಸಾಲಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    loanDetails: "ಸಾಲದ ವಿವರಗಳು",
    amount: "ಮೊತ್ತ",
    rate: "ಬಡ್ಡಿ ದರ",
    status: "ಸ್ಥಿತಿ",
    financialHealth: "ಹಣಕಾಸು ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    healthStatusExcellent: "ಅತ್ಯುತ್ತಮ ಸ್ಥಿತಿ",
    healthStatusModerate: "ಮಧ್ಯಮ ಆರೋಗ್ಯ",
    healthStatusRisk: "ಅಪಾಯದ ಪ್ರೊಫೈಲ್ ಪತ್ತೆಯಾಗಿದೆ",
    healthDesc: "ನಿಮ್ಮ ಉಳಿತಾಯದ ವ್ಯಾಪ್ತಿಯು ಸಕ್ರಿಯ ಇಎಂಐಗಳ ವಿರುದ್ಧ ದೃಢವಾಗಿದೆ.",
    trajectory: "ಸಾಲದ ಒತ್ತಡದ ಪಥ",
    retryConnection: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    reauthenticate: "ಮತ್ತೆ ಲಾಗ್ ಇನ್ ಮಾಡಿ",
    failedSync: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸಿಂಕ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ",
    hideSummary: "ಸಾರಾಂಶ ಮರೆಮಾಡು",
    inAppSummary: "ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿನ ಹಣಕಾಸು ಸಾರಾಂಶ",
    confidentialAudit: "ರಹಸ್ಯ ಆಡಿಟ್",
    deductionsSummary: "ಕಡಿತಗಳ ಸಾರಾಂಶ",
    grossSalaryLabel: "ಒಟ್ಟು ಸಂಬಳ:",
    pfLabel: "ಭವಿಷ್ಯ ನಿಧಿ (PF):",
    ptLabel: "ವೃತ್ತಿಪರ ತೆರಿಗೆ:",
    itLabel: "ಆದಾಯ ತೆರಿಗೆ:",
    netTakeHomeLabel: "ನಿವ್ವಳ ಸಂಬಳ:",
    expenseAllocations: "ವೆಚ್ಚ ಹಂಚಿಕೆಗಳು",
    coreTotal: "ಒಟ್ಟು ವೆಚ್ಚ:",
    surplusHeadroom: "ಉಳಿದಿರುವ ಹಣ:",
    dtiRatioLabel: "ಡಿಟಿಐ ಅನುಪಾತ:",
    savingsRateLabel: "ಉಳಿತಾಯ ದರ:",
    advisorRec: "ಸಲಹೆಗಾರರ ಶಿಫಾರಸುಗಳು",
    savingsCatStatus: "ಉಳಿತಾಯ ವರ್ಗದ ಸ್ಥಿತಿ:",
    combinedRiskFactor: "ಒಟ್ಟು ಅಪಾಯದ ಅಂಶ:",
    dtiTip: "ಸಾಲದ ಒತ್ತಡ ತಪ್ಪಿಸಲು ಡಿಟಿಐ ಅನುಪಾತವನ್ನು 30% ಕ್ಕಿಂತ ಕಡಿಮೆ ಇಟ್ಟುಕೊಳ್ಳಿ.",
    howToUseTitle: "ಸ್ಮಾರ್ಟ್ ಲೋನ್ ಅನಾಲಿಜರ್ ಬಳಸುವುದು ಹೇಗೆ",
    howToUseDesc: "ವೇದಿಕೆಗೆ ಸ್ವಾಗತ. ನಮ್ಮ ನೈಜ ಮಾರ್ಗದರ್ಶಿ ಪ್ರೊಫೈಲ್ ಜಾನ್ (28 ವರ್ಷ, ಸಂಬಳ ಪಡೆಯುವ ಉದ್ಯೋಗಿ) ಬಳಸಿ ಪ್ರವಾಸ ಆರಂಭಿಸಿ. ವೀಕ್ಷಿಸಲು ವಾಕ್‌ಥ್ರೂ ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ!",
    step1Title: "ಹಂತ 1: ನೋಂದಣಿ/ಲಾಗಿನ್",
    step1Desc: "ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ ಅಥವಾ ಲಾಗಿನ್ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ. ಉದಾಹರಣೆ ಪ್ರೊಫೈಲ್: ಇಮೇಲ್ john@example.com / ಪಾಸ್‌ವರ್ಡ್ John123.",
    step2Title: "ಹಂತ 2: ಸಂಬಳ ಸಂರಚನೆ",
    step2Desc: "ಒಟ್ಟು ಸಂಬಳವನ್ನು ನಮೂದಿಸಿ (₹60,000). ವ್ಯವಸ್ಥೆಯು ಸ್ವಯಂಚಾಲಿತವಾಗಿ 12% PF (₹7,200), PT (₹200) ಮತ್ತು IT (₹2,000) ಕಡಿತಗೊಳಿಸಿ ನಿವ್ವಳ ಸಂಬಳ ₹50,600 ಅನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡುತ್ತದೆ.",
    step3Title: "ಹಂತ 3: ವೆಚ್ಚಗಳ ಟ್ರ್ಯಾಕಿಂಗ್",
    step3Desc: "ತಿಂಗಳ ವೆಚ್ಚಗಳನ್ನು ನಮೂದಿಸಿ: ಬಾಡಿಗೆ (₹15k), ಆಹಾರ (₹6k), ಸಾರಿಗೆ (₹2k), ವಿದ್ಯುತ್ (₹1.5k), ಇಂಟರ್ನೆಟ್ (₹800), ವಿಮೆ (₹2k), ಮತ್ತು ಇತರ ವೆಚ್ಚಗಳು (₹3k) ಸೇರಿ ಒಟ್ಟು ₹30,300 ವೆಚ್ಚವಾಗುತ್ತದೆ.",
    step4Title: "ಹಂತ 4: ನಿವ್ವಳ ಉಳಿತಾಯ",
    step4Desc: "ನಿವ್ವಳ ಸಂಬಳ (₹50,600) ಮೈನಸ್ ವೆಚ್ಚಗಳು (₹30,300) ಕಳೆದರೆ ಉಳಿಯುವ ಮೊತ್ತ ₹20,300. ಇದು ನಿಮ್ಮ ಸಾಲ ಪಡೆಯುವ ಸಾಮರ್ಥ್ಯವನ್ನು ನಿರ್ಧರಿಸುತ್ತದೆ.",
    guidedJourneyTitle: "ಸಂವಾದಾತ್ಮಕ ಮಾರ್ಗದರ್ಶಿ ಪ್ರವಾಸ",
    guidedJourneyDesc: "ನಾವು ಸಂಪೂರ್ಣ ವಾಕ್‌ಥ್ರೂ ಪುಟವನ್ನು ನಿರ್ಮಿಸಿದ್ದೇವೆ. ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ನೇರವಾಗಿ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ.",
    startWalkthroughBtn: "ವಾಕ್‌ಥ್ರೂ ಪ್ರಾರಂಭಿಸಿ 🚀",
    leafletLandmarks: "ಮಾರ್ಗದ ಹಂತಗಳು:",
    leafletLandmarksDesc: "• ಖಾತೆ ಸೆಟಪ್ ಮತ್ತು ಆದಾಯ • ವೆಚ್ಚಗಳು ಮತ್ತು ಉಳಿತಾಯ ಟ್ರ್ಯಾಕಿಂಗ್ • ಸಾಲ ಲೆಕ್ಕಾಚಾರ ಮತ್ತು ಆರೋಗ್ಯ ತಪಾಸಣೆ",
    netSalaryCardTitle: "ನಿವ್ವಳ ಸಂಬಳ",
    afterDeductions: "ಪಿಎಫ್ ಮತ್ತು ತೆರಿಗೆ ಕಡಿತದ ನಂತರ",
    totalMonthlyExpensesTitle: "ಒಟ್ಟು ಮಾಸಿಕ ವೆಚ್ಚಗಳು",
    coreOutflowsTracked: "ವೆಚ್ಚಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲಾಗಿದೆ",
    disposableBufferTitle: "ಉಳಿದಿರುವ ಆದಾಯ",
    freeCashSurplus: "ಉಳಿದ ನಗದು",
    monthlyActiveEmisTitle: "ಸಕ್ರಿಯ ಮಾಸಿಕ ಇಎಂಐಗಳು",
    financesAllocProfile: "ಹಣಕಾಸು ಹಂಚಿಕೆ ವಿವರ",
    financesAllocProfileDesc: "ಆದಾಯ, ವೆಚ್ಚಗಳು ಮತ್ತು ಸಾಲದ ಬಾಧ್ಯತೆಗಳ ಹೋಲಿಕೆ.",
    expensesDistTitle: "ವೆಚ್ಚಗಳ ವಿತರಣೆ",
    expensesDistDesc: "ವೆಚ್ಚಗಳ ವರ್ಗವಾರು ವಿಭಜನೆ.",
    noExpensesConfigured: "ಇನ್ನೂ ಯಾವುದೇ ವೆಚ್ಚಗಳನ್ನು ಸಂರಚಿಸಲಾಗಿಲ್ಲ",
    derivedHealthScore: "ಉಳಿತಾಯ ಸಾಮರ್ಥ್ಯ, ವೆಚ್ಚದ ಮಿತಿಗಳು ಮತ್ತು ಸಾಲದ ಅನುಪಾತದ ಆಧಾರದ ಮೇಲೆ ಇದನ್ನು ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ.",
    healthRatingLabel: "ಆರೋಗ್ಯ ರೇಟಿಂಗ್",
    computeLoanAffordability: "ಸಾಲದ ಭರಿಸುವಿಕೆ ಲೆಕ್ಕ ಹಾಕಿ",
    calcMonthlyEmi: "ಲೆಕ್ಕಹಾಕಿದ ಮಾಸಿಕ ಇಎಂಐ",
    totalInterestPaid: "ಒಟ್ಟು ಪಾವತಿಸಿದ ಬಡ್ಡಿ:",
    totalCumRepayment: "ಒಟ್ಟು ಮರುಪಾವತಿ ಮೊತ್ತ:",
    affordabilityAnalysisTitle: "ಭರಿಸುವ ಸಾಮರ್ಥ್ಯದ ವಿಶ್ಲೇಷಣೆ",
    highlyAffordable: "ಸುಲಭವಾಗಿ ಭರಿಸಬಹುದು ✅",
    emiDispPercentage: "ಇಎಂಐ ನಿಮ್ಮ ಉಳಿದಿರುವ ಆದಾಯದ {percent}% ಆಗಿದೆ.",
    riskyLeverage: "ಅಪಾಯಕಾರಿ ಪ್ರಮಾಣ ⚠️",
    emiRiskyPercentage: "ಇಎಂಐ ಉಳಿದಿರುವ ಆದಾಯದ {percent}% ಅನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ. ಜಾಗರೂಕರಾಗಿರಿ.",
    notAffordable: "ಭರಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ ❌",
    emiNotAffordablePercentage: "ಇಎಂಐ ಉಳಿದಿರುವ ಆದಾಯದ 50% ಕ್ಕಿಂತ ({percent}%) ಹೆಚ್ಚಾಗಿದೆ. ಸಾಲ ನಿರಾಕರಿಸಲು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    configFinancialProfile: "ಹಣಕಾಸಿನ ಪ್ರೊಫೈಲ್ ಸಂರಚಿಸಿ",
    specifyIncomeExpenses: "ವಿವರವಾದ ಆದಾಯ ಘಟಕಗಳು ಮತ್ತು ವೆಚ್ಚಗಳನ್ನು ನಮೂದಿಸಿ.",
    salaryModuleStructure: "ಸಂಬಳದ ವಿಭಾಗ",
    grossSalaryInput: "ಒಟ್ಟು ಸಂಬಳ",
    pfRateInput: "ಪಿಎಫ್ ದರ (%)",
    ptInputLabel: "ವೃತ್ತಿಪರ ತೆರಿಗೆ (PT)",
    itInputLabel: "ಆದಾಯ ತೆರಿಗೆ (IT)",
    itemizedExpensesTracking: "ವೆಚ್ಚಗಳ ವಿವರ",
    monthlyRentInput: "ಮಾಸಿಕ ಬಾಡಿಗೆ",
    foodGroceriesInput: "ಆಹಾರ ಮತ್ತು ದಿನಸಿ",
    transportInputLabel: "ಸಾರಿಗೆ ವೆಚ್ಚ",
    electricityInputLabel: "ವಿದ್ಯುತ್ ಬಿಲ್",
    internetInputLabel: "ಇಂಟರ್ನೆಟ್ / ವೈಫೈ",
    insuranceInputLabel: "ವಿಮೆ",
    otherExpensesInputLabel: "ಇತರ ವೆಚ್ಚಗಳು",
    savingFinancials: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    saveFinancialsBtn: "ಹಣಕಾಸಿನ ವಿವರಗಳನ್ನು ಉಳಿಸಿ",

    // Goals
    goalsTitle: "ಭಾವನಾತ್ಮಕ ಹಣದ ಟೈಮ್‌ಲೈನ್",
    goalsDesc: "ಉಳಿತಾಯ ಗುರಿಗಳನ್ನು ವ್ಯಾಖ್ಯಾನಿಸಿ ಮತ್ತು ಹೊಂದಿಕೊಳ್ಳುವ ವೆಚ್ಚಗಳ ವಿರುದ್ಧ ಖರೀದಿ ದಿನಾಂಕಗಳನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ.",
    createGoal: "ಗುರಿಯನ್ನು ರಚಿಸಿ",
    goalIdentifier: "ಗುರಿಯ ಹೆಸರು",
    targetCost: "ಗುರಿಯ ವೆಚ್ಚ ($)",
    monthlyContribution: "ಮಾಸಿಕ ಕೊಡುಗೆ",
    addTargetGoal: "ಗುರಿಯನ್ನು ಸೇರಿಸಿ",
    forecastOnline: "ಟೈಮ್‌ಲೈನ್ ಮುನ್ಸೂಚನೆ",

    // Fraud
    fraudTitle: "ಎಐ ವಹಿವಾಟು ಕಾವಲುಗಾರ",
    fraudDesc: "ವಹಿವಾಟು ಇತ್ಯರ್ಥಪಡಿಸುವ ಮೊದಲು ಹೆಚ್ಚಿನ ಅಪಾಯದ ಪಾವತಿಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ.",
    analyzePayment: "ಪಾವತಿ ಮಾನದಂಡಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    settlementAmount: "ಪಾವತಿ ಮೊತ್ತ ($)",
    category: "ವರ್ಗ",
    merchant: "ಸ್ವೀಕರಿಸುವ ವ್ಯಾಪಾರಿ",
    merchantLoc: "ವ್ಯಾಪಾರಿಯ ಸ್ಥಳ",
    analyzeSettlement: "ಪಾವತಿ ವಿಶ್ಲೇಷಿಸಿ",
    neuralEngine: "ಎಐ ಎಂಜಿನ್ ಸಕ್ರಿಯವಾಗಿದೆ",

    // Family Finance
    familyTitle: "ಕುಟುಂಬ ಹಣಕಾಸು ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    familyDesc: "ಹಂಚಿಕೊಂಡ ವಾಲೆಟ್‌ಗಳು, ಕೌಟುಂಬಿಕ ಮಿತಿಗಳು, ಹಿರಿಯರ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಗುಂಪು ಉಳಿತಾಯ ಯೋಜನೆಗಳನ್ನು ಸಂಘಟಿಸಲು ಖಾತೆಗಳನ್ನು ಲಿಂಕ್ ಮಾಡಿ.",
    groupManagement: "ಗುಂಪು ನಿರ್ವಹಣೆ",
    establishGroup: "ಗುಂಪನ್ನು ಸ್ಥಾಪಿಸಿ",
    establishGroupDesc: "ಸುರಕ್ಷಿತ ಹಂಚಿಕೆಯ ಹಣಕಾಸು ಕಾರ್ಯಕ್ಷೇತ್ರವನ್ನು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ತಕ್ಷಣವೇ ಆಮಂತ್ರಣ ಲಿಂಕ್‌ಗಳನ್ನು ನೀಡಿ.",
    createNewEcosystem: "ಹೊಸ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯನ್ನು ರಚಿಸಿ",
    ecosystemConnectionId: "ಪರಿಸರ ವ್ಯವಸ್ಥೆಯ ಸಂಪರ್ಕ ಐಡಿ",
    provideConnectionIdDesc: "ಹಂಚಿಕೆಯ ವಾಲೆಟ್ ಸೂಚ್ಯಂಕಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಸಕ್ರಿಯ ಕುಟುಂಬ ಟೋಕನ್ ಐಡಿಯನ್ನು ಒದಗಿಸಿ.",
    synchronizeGroup: "ಗುಂಪನ್ನು ಸಿಂಕ್ರೊನೈಸ್ ಮಾಡಿ",
    synching: "ಸಿಂಕ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    inviteCode: "ಆಮಂತ್ರಣ ಕೋಡ್: ",
    shareCodeWithFamily: "ಕುಟುಂಬದೊಂದಿಗೆ ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಿ",
    sharedBalance: "ಹಂಚಿಕೆಯ ಬಾಕಿ",
    topUp: "+ ಟಾಪ್ ಅಪ್",
    amountVal: "ಮೊತ್ತ ($)",
    primaryPool: "ಪ್ರಾಥಮಿಕ ಪೂಲ್",
    activeWallet: "ಸಕ್ರಿಯ ವಾಲೆಟ್",
    ecosystemMembers: "ಪರಿಸರ ವ್ಯವಸ್ಥೆಯ ಸದಸ್ಯರು",
    connected: "ಸಂಪರ್ಕಿತ",
    recentTransactions: "ಇತ್ತೀಚಿನ ಕುಟುಂಬ ಪೂಲ್ ವಹಿವಾಟುಗಳು",
    liveLedger: "ಲೈವ್ ಲೆಡ್ಜರ್",
    member: "ಸದಸ್ಯರು",
    reason: "ಕಾರಣ",
    date: "ದಿನಾಂಕ",
    noTransactions: "ಇನ್ನೂ ಯಾವುದೇ ವಹಿವಾಟುಗಳು ದಾಖಲಾಗಿಲ್ಲ.",
    addMember: "ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ",
    inviteMemberDesc: "ಮಿತಿಗಳು ಮತ್ತು ಹಿರಿಯರ ವೆಚ್ಚಗಳನ್ನು ಸಂಘಟಿಸಲು ಅವರ ಇಮೇಲ್ ಬಳಸಿ ಸದಸ್ಯರನ್ನು ಆಹ್ವಾನಿಸಿ.",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    nickname: "ಅಡ್ಡಹೆಸರು",
    role: "ಪಾತ್ರ",
    monthlyLimit: "ಮಾಸಿಕ ಮಿತಿ ($)",
    parent: "ಪೋಷಕರು",
    child: "ಮಗು",
    elder: "ಹಿರಿಯರು",
    sendingInvite: "ಆಹ್ವಾನಿಸಲಾಗುತ್ತಿದೆ...",
    inviteSuccess: "ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!",

    // Emergency Fund
    fundTitle: "ತುರ್ತು ಹಂಚಿಕೆ ವಾಲೆಟ್ ಮತ್ತು ನಿಧಿ",
    fundDesc: "ನಿಮ್ಮ ಪ್ರಮುಖ ಹಣವನ್ನು ಕಾಯ್ದಿರಿಸಿ. ರನ್‌ವೇ ಅಂದಾಜನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಸಾಲದ ಒತ್ತಡವನ್ನು ತಪ್ಪಿಸಲು ಮಾಸಿಕ ಕೊಡುಗೆ ನೀಡಿ.",
    fundBalance: "ನಿಧಿ ಬಾಕಿ",
    monthsOfRunway: "ರನ್‌ವೇಯ ತಿಂಗಳುಗಳು",
    runwayDesc: "ಪ್ರಸ್ತುತ ಬಾಕಿ ಮತ್ತು ವೆಚ್ಚಗಳ ಆಧಾರದ ಮೇಲೆ ಉಳಿಯುವ ಅಂದಾಜು ತಿಂಗಳುಗಳು.",
    fundGoal: "ನಿಧಿಯ ಗುರಿ",
    monthlyContributionGraph: "ಮಾಸಿಕ ಕೊಡುಗೆಯ ಪ್ರಗತಿ",
    contribute: "ನಿಧಿಗೆ ಕೊಡುಗೆ ನೀಡಿ",
    withdraw: "ತುರ್ತು ಹಿಂಪಡೆಯುವಿಕೆ",

    // Simulation
    simTitle: "ವಡ್ಡಿ ದರ ಸಿಮ್ಯುಲೇಟರ್",
    simDesc: "ಅಸಲು ಬದಲಾವಣೆಗಳು, ಬಡ್ಡಿ ಬದಲಾವಣೆಗಳು ಅಥವಾ ಅವಧಿಗೆ ಮುನ್ನ ಪಾವತಿಗಳಂತಹ ರಚನಾತ್ಮಕ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ.",
    loanDetailsForm: "ಸಾಲದ ನಿಯತಾಂಕಗಳು",
    simulateButton: "ಸಿಮ್ಯುಲೇಶನ್ ರನ್ ಮಾಡಿ",
    simResults: "ಸಿಮ್ಯುಲೇಶನ್ ಒಳನೋಟಗಳು ಮತ್ತು ಮೆಟ್ರಿಕ್ಸ್",

    // Stress Analysis
    stressTitle: "ಸಾಲದ ಒತ್ತಡ ಮತ್ತು ದುರ್ಬಲತೆಯ ತಪಾಸಣೆ",
    stressDesc: "ವಿವಿಧ ಆರ್ಥಿಕ ಆಘಾತಗಳ ಅಡಿಯಲ್ಲಿ ನಿಮ್ಮ ನಗದು ಹರಿವು ಎಷ್ಟು ದುರ್ಬಲವಾಗಿದೆ ಎಂಬುದನ್ನು ವಿಶ್ಲೇಷಿಸಿ.",
    runStressCheck: "ದುರ್ಬಲತೆಯ ಸ್ಕ್ಯಾನ್ ರನ್ ಮಾಡಿ",

    // Voice Tracker
    voiceTitle: "ಧ್ವನಿ ಸಾಲದ ಸಹಾಯಕ",
    voiceDesc: "ನೈಸರ್ಗಿಕ ಧ್ವನಿ ವಾಕ್ಯಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಸಾಲದ ವ್ಯವಸ್ಥಾಪಕರಿಗೆ ಆದೇಶಿಸಿ. ನೈಜ-ಸಮಯದ ಎನ್‌ಎಲ್‌ಪಿ ಪಾರ್ಸಿಂಗ್ ಕಾರ್ಯಗತಗೊಳಿಸಬಹುದಾದ ಈವೆಂಟ್‌ಗಳನ್ನು ಹೊರತೆಗೆಯುತ್ತದೆ.",
    speakCommand: "ಆದೇಶವನ್ನು ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    listening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...",

    // General UI
    save: "ಉಳಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    loadingVal: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    backToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    inviteCodeRequired: "ಸಿಂಕ್ ಮಾಡಲು ಗ್ರೂಪ್ ಐಡಿ ಅಗತ್ಯವಿದೆ",

    // Loans
    manageLoansLocally: "ನಿಮ್ಮ ಸಾಲಗಳನ್ನು ಸ್ಥಳೀಯವಾಗಿ ನಿರ್ವಹಿಸಿ. ಸಿಮ್ಯುಲೇಶನ್ ಬ್ಯಾಕೆಂಡ್ ಅನ್ನು ಬಳಸುತ್ತದೆ.",
    addNewLoan: "ಹೊಸ ಸಾಲವನ್ನು ಸೇರಿಸಿ",
    loanType: "ಸಾಲದ ಪ್ರಕಾರ",
    loanTypePlaceholder: "ಉದಾಹರಣೆಗೆ, ಗೃಹ ಸಾಲ",
    amountPlaceholder: "150000",
    interestPlaceholder: "3.5",
    durationPlaceholder: "240",
    adding: "ಸೇರಿಸಲಾಗುತ್ತಿದೆ...",
    addLoanButton: "ಸಾಲ ಸೇರಿಸಿ",
    yourLoans: "ನಿಮ್ಮ ಸಾಲಗಳು",
    noLoans: "ಇನ್ನೂ ಯಾವುದೇ ಸಾಲಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.",
    amountLabel: "ಮೊತ್ತ",
    interestLabel: "ಬಡ್ಡಿ",
    durationLabel: "ಅವಧಿ",
    statusLabel: "ಸ್ಥಿತಿ",

    // Simulation Additional
    simSandbox: "ಸಂವಾದಾತ್ಮಕ ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್",
    simMainTitle: "ಹಣಕಾಸು ಸನ್ನಿವೇಶ ಸಿಮ್ಯುಲೇಟರ್",
    simDescExtended: "ಮೊತ್ತದ ಮುಂಗಡ ಪಾವತಿ, ಇಎಂಐ ಹೊಂದಾಣಿಕೆಗಳು ಮತ್ತು ಬಡ್ಡಿ ಉಳಿತಾಯವನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಲು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ.",
    scenarioParams: "ಸನ್ನಿವೇಶ ನಿಯತಾಂಕಗಳು",
    scenarioDesc: "ಪಾವತಿ ವೇಳಾಪಟ್ಟಿಗಳನ್ನು ಪರೀಕ್ಷಿಸಲು ಇನ್‌ಪುಟ್‌ಗಳನ್ನು ಹೊಂದಿಸಿ ಅಥವಾ ನಿಖರ ಸ್ಲೈಡರ್‌ಗಳನ್ನು ಬಳಸಿ.",
    loanPrincipal: "ಸಾಲದ ಅಸಲು ಮೊತ್ತ ($)",
    tenureHorizon: "ಅವಧಿ ಹಾರಿಜಾನ್ (ತಿಂಗಳುಗಳು)",
    tenure1Year: "೧ ವರ್ಷ (೧೨ತಿಂಗಳು)",
    tenure15Years: "೧೫ ವರ್ಷಗಳು (೧೮೦ತಿಂಗಳು)",
    tenure30Years: "೩招 ವರ್ಷಗಳು (೩೬೦ತಿಂಗಳು)",
    payoffBoosters: "ಒಂದು ವೇಳೆ ಹೆಚ್ಚುವರಿ ಪಾವತಿ ಮಾಡಿದರೆ",
    extraMonthlyPayoff: "ಹೆಚ್ಚುವರಿ ಮಾಸಿಕ ಪಾವತಿ ($)",
    oneTimePrepayment: "ಒಂದು ಬಾರಿಯ ಮುಂಗಡ ಪಾವತಿ ($)",
    simCompounding: "ಮರುಪಾವತಿ ಉಳಿತಾಯವನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    runSandbox: "ಸಿಮ್ಯುಲೇಶನ್ ರನ್ ಮಾಡಿ",
    calcException: "Calculation Exception",
    waitingScenario: "ಮರುಪಾವತಿ ಸನ್ನಿವೇಶಕ್ಕಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    waitingScenarioDesc: "ನಿಮ್ಮ ಸಿಮ್ಯುಲೇಶನ್ ಮೆಟ್ರಿಕ್ಸ್ ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು 'ಸಿಮ್ಯುಲೇಶನ್ ರನ್ ಮಾಡಿ' ಕ್ಲಿಕ್ ಮಾಡಿ.",
    interestSavings: "ಬಡ್ಡಿ ಉಳಿತಾಯ",
    interestSavingsDesc: "ಮುಂಚಿತವಾಗಿ ಮರುಪಾವತಿ ಮಾಡುವುದರಿಂದ ಬಡ್ಡಿ ಹೇಗೆ ಕಡಿಮೆಯಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ನೋಡಿ.",
    timelineShortening: "ಅವಧಿ ಕಡಿತ",
    timelineShorteningDesc: "ಮಾಸಿಕ ಬಫರ್‌ಗಳನ್ನು ರೂಪಿಸಿ ಮತ್ತು ಸಾಲಮುಕ್ತ ದಿನಾಂಕವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    compoundingBenefit: "ಸಂಯುಕ್ತ ಬಡ್ಡಿಯ ಪ್ರಯೋಜನ",
    repaymentSummary: "ಮರುಪಾವತಿ ಸಾರಾಂಶ",
    highOptimization: "ಹೆಚ್ಚಿನ ಆಪ್ಟಿಮೈಸೇಶನ್",
    projectedInterestSaved: "Projected Interest Saved",
    interestSavedDesc: "ಇದು ಬಡ್ಡಿ ಶುಲ್ಕಗಳಿಗೆ ಹೋಗುವ ಬದಲಿಗೆ ನಿಮ್ಮ ವಾಲೆಟ್‌ನಲ್ಲಿ ಉಳಿಯುವ ಒಟ್ಟು ಹಣವಾಗಿದೆ.",
    newMonthlyEmi: "ಹೊಸ ಮಾಸಿಕ ಇಎಂಐ",
    remainingHorizon: "ಉಳಿದಿರುವ ಮರುಪಾವತಿ ಅವಧಿ",
    optimizedDate: "Optimized Debt-Free Date",
    payoffComparison: "ಮರುಪಾವತಿ ಅವಧಿಯ ಹೋಲಿಕೆ",
    originalHorizon: "Original Horizon",
    optimizedHorizon: "Optimized Horizon",
    quicker: "ವೇಗವಾಗಿ!",
    aiScenarioCounsel: "ಎಐ ಸನ್ನಿವೇಶ ಸಲಹೆ",
    synthesizingData: "ಡೇಟಾ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    retriggerAI: "ಎಐ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಮರು-ಪ್ರಚೋದಿಸಿ",

    // Stress Analysis Additional
    coreRiskDiagnostic: "Core Risk Diagnostic",
    debtStressAnalysisTitle: "ಸಾಲದ ಒತ್ತಡದ ವಿಶ್ಲೇಷಣೆ",
    debtStressDescExtended: "ನಿಮ್ಮ ಮಾಸಿಕ ಸಾಲದ ಬದ್ಧತೆಗಳು ನಿಮ್ಮ ನಗದು ಹರಿವಿನ ಮೇಲೆ ಎಷ್ಟು ಒತ್ತಡ ಹೇರುತ್ತವೆ ಎಂಬುದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
    incomeMinusExpenses: "Income minus fixed expenses",
    activeLoanPayments: "ಎಲ್ಲಾ ಸಕ್ರಿಯ ಸಾಲ ಪಾವತಿಗಳ ಮೊತ್ತ",
    disposableCashflow: "Disposable Cashflow",
    totalMonthlyEmi: "ಒಟ್ಟು ಮಾಸಿಕ ಇಎಂಐ",
    combinedStressScore: "Combined Stress Score",
    debtToDisposableRatio: "Debt-to-disposable ratio",
    historicalTrend: "Historical Risk Amortization Trend",
    timelineTrackStress: "Timeline track of your debt stress score index.",
    stressContribution: "Stress Contribution by Individual Loan",
    isolatedImpactScore: "Isolated impact score of each active loan item on your cashflow.",
    activeObligation: "Active Obligation",
    stressRatio: "ಒತ್ತಡದ ಅನುಪಾತ",
    noLoansDetected: "ಯಾವುದೇ ಸಾಲಗಳು ಪತ್ತೆಯಾಗಿಲ್ಲ",
    noLoansDetectedDesc: "Add amortized loan liabilities on the Loan Ledger page to review stress audits.",
    primaryStressDriver: "Primary Stress Driver",
    contributesLargest: "contributes the single largest cashflow pressure point",
    ratioText: "individual ratio.",
    debtDisposableRatioText: "Debt-to-Disposable Cashflow Ratio:",
    consumeDisposable: "Your amortized EMIs consume",
    safeCashflowRunway: "Safe Cashflow Runway:",
    preserveMonthlyNet: "You preserve a monthly net cash balance of",
    discretionarySavings: "for savings and discretionary activities.",
    cashflowAlert: "Cashflow Alert",
    stressExceedsWarning: "ನಿಮ್ಮ ಸಾಲದ ಒತ್ತಡದ ಅನುಪಾತವು ಶಿಫಾರಸು ಮಾಡಲಾದ 35% ಮಿತಿಯನ್ನು ಮೀರಿದೆ. ಮರುಪಾವತಿ ಅಥವಾ ಮರುಹಣಕಾಸು ಮಾಡಲು ಸೂಚಿಸಲಾಗುತ್ತದೆ.",

    // Walkthrough content
    w_welcome_title: "👋 ಸ್ವಾಗತ ಜಾನ್!",
    w_welcome_subtitle: "ನಿಮ್ಮ ಮಾರ್ಗದರ್ಶಿ ಸಂಗಾತಿಯನ್ನು ಭೇಟಿ ಮಾಡಿ",
    w_welcome_desc: "ಹಾಯ್, ನಾನು ಜಾನ್. ಸ್ಮಾರ್ಟ್ ಲೋನ್ ಅನಾಲಿಜರ್ ನನ್ನ ಹಣವನ್ನು ನಿರ್ವಹಿಸಲು ನನಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ ಎಂದು ನಾನು ನಿಮಗೆ ತೋರಿಸುತ್ತೇನೆ.",
    w_welcome_label: "ಪ್ರೊಫೈಲ್ ಸಾರಾಂಶ",
    w_welcome_body: "ವಯಸ್ಸು: 28 ವರ್ಷ \nವೃತ್ತಿ: ಸಂಬಳ ಪಡೆಯುವ ಉದ್ಯೋಗಿ \nಗುರಿ: ಹಣವನ್ನು ಉಳಿಸಿ, ಸಾಲದ ಒತ್ತಡದಿಂದ ಪಾರಾಗಿ ಮತ್ತು ಹೊಸ ಬೈಕ್ ಖರೀದಿಸಿ.",
    w_welcome_footer: "🎯 ಪ್ರವಾಸದ ಗುರಿ: ನಗದು ಮೀಸಲು ಆರೋಗ್ಯಕರವಾಗಿಡುವುದು",

    w_account_title: "👤 ಖಾತೆ ರಚಿಸಿ",
    w_account_subtitle: "ಹಣಕಾಸಿನ ಸುರಕ್ಷತೆಗೆ ಮೊದಲ ಹೆಜ್ಜೆ",
    w_account_desc: "ಮೊದಲಿಗೆ ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ ಇದರಿಂದ ನೀವು ಯಾರೆಂದು ಅಪ್ಲಿಕೇಶನ್ ತಿಳಿಯುತ್ತದೆ.",
    w_account_label: "ನೋಂದಣಿ",
    w_account_footer: "ಪರಿಶೀಲಿಸಿದ ಡೆಮೊ ಪ್ರೊಫೈಲ್ ವಿವರಗಳು",

    w_salary_title: "💰 ಸಂಬಳದ ವಿಭಾಗ",
    w_salary_subtitle: "ಒಟ್ಟು ಸಂಬಳ vs ನಿವ್ವಳ ಸಂಬಳ",
    w_salary_desc: "ಜಾನ್ ಸಂಬಳದ ವಿಭಾಗವನ್ನು ತಲುಪುತ್ತಾನೆ 💰. ನಾನು ಮೊದಲು ನನ್ನ ಮಾಸಿಕ ಸಂಬಳವನ್ನು ಸೇರಿಸುತ್ತೇನೆ.",
    w_salary_label: "ಸಂಬಳ ವಿಭಜನೆ",

    w_expense_title: "🏠 ವೆಚ್ಚಗಳ ವಿಭಾಗ",
    w_expense_subtitle: "ವೆಚ್ಚಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    w_expense_desc: "ಜಾನ್ ವೆಚ್ಚಗಳ ವಿಭಾಗಕ್ಕೆ ಚಲಿಸುತ್ತಾನೆ 🏠. ನನ್ನ ಹಣ ಪ್ರತಿ ತಿಂಗಳು ಎಲ್ಲಿಗೆ ಹೋಗುತ್ತದೆ ಎಂಬುದನ್ನು ನಾನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತೇನೆ.",
    w_expense_label: "ವೆಚ್ಚದ ಐಟಂಗಳು",

    w_savings_title: "📊 ನಿವ್ವಳ ಉಳಿತಾಯ",
    w_savings_subtitle: "ಉಳಿದಿರುವ ನಗದು",
    w_savings_desc: "ಜಾನ್ ಉಳಿತಾಯ ವಿಭಾಗಕ್ಕೆ ಚಲಿಸುತ್ತಾನೆ 📊. ನಾನು ಎಷ್ಟು ಹಣವನ್ನು ಉಳಿಸಬಹುದು ಎಂದು ಇದು ನನಗೆ ತಿಳಿಸುತ್ತದೆ.",
    w_savings_label: "ಉಳಿತಾಯ ಬಫರ್",

    w_loan_title: "🏦 ಸಾಲದ ಲೆಕ್ಕಾಚಾರ",
    w_loan_subtitle: "ಇಎಂಐ ಲೆಕ್ಕಾಚಾರ ಮತ್ತು ಸಿಮ್ಯುಲೇಶನ್",
    w_loan_desc: "ಜಾನ್ ಸಾಲ ಲೆಕ್ಕಾಚಾರ ವಿಭಾಗ ತಲುಪುತ್ತಾನೆ 🏦. ಸಾಲ ಪಡೆಯುವ ಮುನ್ನ ನಾನು ಅದನ್ನು ಭರಿಸಬಲ್ಲೆನೇ ಎಂದು ಪರಿಶೀಲಿಸುತ್ತೇನೆ.",
    w_loan_label: "ಬೈಕ್ ಸಾಲದ ಸಿಮ್ಯುಲೇಶನ್",

    w_stress_title: "⚠️ ಸಾಲದ ಒತ್ತಡ ವಿಶ್ಲೇಷಣೆ",
    w_stress_subtitle: "ಸಂಬಳದಲ್ಲಿ ಸಾಲಕ್ಕೆ ಎಷ್ಟು ಹಣ ಹೋಗುತ್ತದೆ",
    w_stress_desc: "ಜಾನ್ ಸಾಲದ ಒತ್ತಡ ವಿಶ್ಲೇಷಣೆ ತಲುಪುತ್ತಾನೆ ⚠️. ನನ್ನ ಸಾಲಗಳು ಸುರಕ್ಷಿತವೇ ಅಥವಾ ಅಪಾಯಕಾರಿಯೇ ಎಂದು ಅಪ್ಲಿಕೇಶನ್ ತಿಳಿಸುತ್ತದೆ.",
    w_stress_label: "ಒತ್ತಡದ ಮೀಟರ್",

    w_fund_title: "🛟 ತುರ್ತು ನಿಧಿ",
    w_fund_subtitle: "ಅನಿರೀಕ್ಷಿತ ವೆಚ್ಚಗಳಿಗೆ ಸಿದ್ಧತೆ",
    w_fund_desc: "ಜಾನ್ ತುರ್ತು ನಿಧಿ ವಿಭಾಗ ತಲುಪುತ್ತಾನೆ 🛟. ನಾನು ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಳಿಗಾಗಿ ಹಣವನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತೇನೆ.",
    w_fund_label: "ಸುರಕ್ಷತಾ ರನ್‌ವೇ",

    w_goals_title: "🎯 ಆರ್ಥಿಕ ಗುರಿಗಳು",
    w_goals_subtitle: "ಭವಿಷ್ಯದ ಕನಸುಗಳ ಯೋಜನೆ",
    w_goals_desc: "ಜಾನ್ ಆರ್ಥಿಕ ಗುರಿಗಳ ವಿಭಾಗ ತಲುಪುತ್ತಾನೆ 🎯. ನನ್ನ ಭವಿಷ್ಯದ ಗುರಿಗಳನ್ನು ನಾನು ಯೋಜಿಸುತ್ತೇನೆ.",
    w_goals_label: "ಭವಿಷ್ಯದ ಕನಸುಗಳು",

    w_ai_title: "🤖 ಎಐ ಸಹಾಯಕ",
    w_ai_subtitle: "ನಿಮ್ಮ ಹಣಕಾಸು ರೋಬೋಟ್ ಸ್ನೇಹಿತ",
    w_ai_desc: "ಜಾನ್ ಎಐ ಸಹಾಯಕನನ್ನು ಭೇಟಿ ಮಾಡುತ್ತಾನೆ 🤖. ನಾನು ಹಣಕಾಸಿನ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಬಹುದು ಮತ್ತು ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಬಹುದು.",
    w_ai_label: "ಎಐ ಮಾರ್ಗದರ್ಶನ",

    w_dashboard_title: "📈 ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ ಒಳನೋಟಗಳು",
    w_dashboard_subtitle: "ಸಂಪೂರ್ಣ ಹಣಕಾಸು ಆರೋಗ್ಯದ ಅವಲೋಕನ",
    w_dashboard_desc: "ಜಾನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ ತಲುಪುತ್ತಾನೆ 📈. ಈಗ ನಾನು ನನ್ನ ಸಂಪೂರ್ಣ ಹಣಕಾಸಿನ ಆರೋಗ್ಯವನ್ನು ನೋಡಬಹುದು.",
    w_dashboard_label: "ಆರೋಗ್ಯ ಸ್ಥಿತಿ",

    w_prev: "ಹಿಂದಿನ",
    w_next: "ಮುಂದಿನ ಹಂತ",
    w_finish: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಪ್ರವೇಶಿಸಿ",
    w_skip: "ಪ್ರವಾಸವನ್ನು ಬಿಟ್ಟುಬಿಡಿ",
    ef_builder_title: "ತುರ್ತು ನಿಧಿ ಬಿಲ್ಡರ್",
    ef_builder_desc: "6 ತಿಂಗಳ ಸುರಕ್ಷತಾ ನಿವ್ವಳವನ್ನು ನಿರ್ಮಿಸಿ — ನಿಮ್ಮ ವೆಚ್ಚಗಳಿಂದ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ.",
    ef_setup_financials: "ಹಣಕಾಸು ಸ್ಥಾಪನೆ",
    ef_transactions: "ವ್ಯವಹಾರಗಳು",
    ef_add_money: "ಹಣ ಸೇರಿಸಿ",
    ef_withdraw: "ಹಿಂತೆಗೆದುಕೊಳ್ಳಿ",
    ef_current_balance: "ಪ್ರಸ್ತುತ ಬಾಕಿ",
    ef_target_6m: "ಗುರಿ (6 ತಿಂಗಳು)",
    ef_monthly_expenses: "ಮಾಸಿಕ ವೆಚ್ಚಗಳು",
    ef_total_accumulated: "ಒಟ್ಟು ಸಂಗ್ರಹಣೆ",
    ef_progress: "ಪ್ರಗತಿ",
    ef_saved: "ಉಳಿಸಲಾಗಿದೆ",
    ef_complete: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    ef_growth_trend: "ಉಳಿತಾಯ ಬೆಳವಣಿಗೆಯ ಪ್ರವೃತ್ತಿ",
    ef_auto_saving_mode: "ಸ್ವಯಂ ಉಳಿತಾಯ ಮೋಡ್",
    ef_auto_saving_desc: "ಪ್ರತಿ-ವ್ಯವಹಾರದ ರೌಂಡ್-ಅಪ್ ಮೊತ್ತವನ್ನು ನಿಮ್ಮ ನಿಧಿಗೆ ಸೇರಿಸಲಾಗುತ್ತದೆ.",
    ef_support_runway: "ಬೆಂಬಲ ರನ್ವೇ",
    ef_runway_desc_detail: "ಪ್ರಸ್ತುತ ವೆಚ್ಚಗಳಲ್ಲಿ ನಿಮ್ಮ ನಿಧಿಯು ಎಷ್ಟು ತಿಂಗಳುಗಳನ್ನು ಒಳಗೊಳ್ಳುತ್ತದೆ.",
    ef_months: "ತಿಂಗಳುಗಳು",
    ef_fully_protected: "ಸಂಪೂರ್ಣವಾಗಿ ರಕ್ಷಿಸಲಾಗಿದೆ",
    ef_partial_coverage: "ಭಾಗಶಃ ಕವರೇಜ್",
    ef_low_build_now: "ಕಡಿಮೆ — ಈಗಲೇ ನಿರ್ಮಿಸಿ",
    ef_based_on_expenses: "ವೆಚ್ಚಗಳ ಆಧಾರದ ಮೇಲೆ",
    ef_health: "ನಿಧಿಯ ಆರೋಗ್ಯ",
    ef_remaining_to_goal: "ಗುರಿಗೆ ಬಾಕಿ ಉಳಿದಿದೆ",
    ef_autosave_per_txn: "ಪ್ರತಿ ವ್ಯವಹಾರಕ್ಕೆ ಸ್ವಯಂ ಉಳಿತಾಯ",
    ef_add_money_modal_desc: "ನಿಮ್ಮ ತುರ್ತು ನಿಧಿಗೆ ಹಸ್ತಚಾಲಿತವಾಗಿ ಕೊಡುಗೆ ನೀಡಿ.",
    ef_amount_inr: "ಮೊತ್ತ (₹)",
    ef_note_optional: "ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)",
    ef_note_placeholder: "ಉದಾ: ಬೋನಸ್ ಡೆಪಾಸಿಟ್",
    ef_deposit_btn: "ಡೆಪಾಸಿಟ್ ಮಾಡಿ",
    ef_processing: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...",
    ef_withdraw_warning: "ನಿಜವಾದ ತುರ್ತು ಸಂದರ್ಭಗಳಲ್ಲಿ ಮಾತ್ರ ಹಿಂತೆಗೆದುಕೊಳ್ಳಿ.",
    ef_reason_required: "ಕಾರಣ *",
    ef_reason_placeholder: "ಉದಾ: ವೈದ್ಯಕೀಯ ತುರ್ತು",
    ef_withdraw_btn: "ಹಿಂತೆಗೆದುಕೊಳ್ಳಿ",
    ef_financial_setup_title: "ಹಣಕಾಸು ಸೆಟಪ್",
    ef_target_formula: "ನಿಮ್ಮ ಗುರಿ = ಮಾಸಿಕ ವೆಚ್ಚಗಳು × 6 ತಿಂಗಳು.",
    ef_monthly_income_label: "ಮಾಸಿಕ ಆದಾಯ (₹)",
    ef_monthly_expenses_label: "ಮಾಸಿಕ ವೆಚ್ಚಗಳು (₹) *",
    ef_current_savings_label: "ಪ್ರಸ್ತುತ ಉಳಿತಾಯ / ಆರಂಭಿಕ ಬಾಕಿ (₹)",
    ef_calculated_target: "ಲೆಕ್ಕಹಾಕಿದ ಗುರಿ",
    ef_saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    ef_save_setup_btn: "ಹಣಕಾಸು ಸೆಟಪ್ ಉಳಿಸಿ",
    ef_txn_history_title: "ವ್ಯವಹಾರದ ಇತಿಹಾಸ",
    ef_no_txns: "ಇನ್ನೂ ಯಾವುದೇ ವ್ಯವಹಾರಗಳಿಲ್ಲ. ಪ್ರಾರಂಭಿಸಲು ಹಣ ಸೇರಿಸಿ.",
    ef_profile_not_set: "ಹಣಕಾಸು ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಲಾಗಿಲ್ಲ",
    ef_profile_not_set_desc: "ನಿಮ್ಮ ಮಾಸಿಕ ಆದಾಯ ಮತ್ತು ವೆಚ್ಚಗಳನ್ನು ನಮೂದಿಸಲು ಹಣಕಾಸು ಸ್ಥಾಪನೆ ಕ್ಲಿಕ್ ಮಾಡಿ. ನಿಮ್ಮ 6 ತಿಂಗಳ ಗುರಿಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ.",
    w_calculated_as: "ಹೀಗೆ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ",
    w_months_plural: "ತಿಂಗಳುಗಳು",
    w_optimize_spends: "ವೆಚ್ಚಗಳನ್ನು ಅತ್ಯುತ್ತಮಗೊಳಿಸುವುದೇ?",
    w_dashboard_footer_msg: "ವಾಕ್‌ಥ್ರೂ ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಳಿಸಲಾಗಿದೆ!",
    w_net: "ನಿವ್ವಳ",
    w_cost: "ವೆಚ್ಚ",
    o_loan_num: "ಸಾಲ #",
    o_click_add_loan: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಇಎಂಐಗಳನ್ನು ನಮೂದಿಸಲು ಸಾಲ ಸೇರಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ",
    g_target: "ಗುರಿ",
    g_saved: "ಉಳಿಸಲಾಗಿದೆ",
    g_monthly: "ಮಾಸಿಕ",
    g_remaining: "ಬಾಕಿ",
    g_progress: "ಪ್ರಗತಿ",
    travel: "ಪ್ರಯಾಣ",
    gadget: "ಗ್ಯಾಜೆಟ್",
    health: "ಆರೋಗ್ಯ"    ,
    g_builder_title: "ನನ್ನ ಗುರಿಗಳು",
    g_builder_desc: "ಉಳಿತಾಯ ಗುರಿಗಳನ್ನು ಹೊಂದಿಸಿ, ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಪ್ರತಿ ಮೈಲಿಗಲ್ಲನ್ನು ತಲುಪಿ.",
    g_new_goal: "ಹೊಸ ಗುರಿ",
    g_total_goals: "ಒಟ್ಟು ಗುರಿಗಳು",
    g_active: "ಸಕ್ರಿಯ",
    g_completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    g_no_goals: "ಇನ್ನೂ ಯಾವುದೇ ಗುರಿಗಳಿಲ್ಲ",
    g_no_goals_desc: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಉಳಿತಾಯ ಗುರಿಯನ್ನು ರಚಿಸಿ.",
    g_create_first: "+ ಮೊದಲ ಗುರಿಯನ್ನು ರಚಿಸಿ",
    g_completed_goals: "ಪೂರ್ಣಗೊಂಡ ಗುರಿಗಳು",
    g_edit: "ತಿದ್ದುಪಡಿ",
    g_complete: "ಪೂರ್ಣಗೊಳಿಸಿ",
    g_delete: "ಅಳಿಸಿ",
    g_icon: "ಚಿಹ್ನೆ",
    g_goal_name: "ಗುರಿಯ ಹೆಸರು *",
    g_target_amount: "ಗುರಿ ಮೊತ್ತ (₹) *",
    g_monthly_contribution: "ಮಾಸಿಕ ಕೊಡುಗೆ (₹) *",
    g_already_saved: "ಈಗಾಗಲೇ ಉಳಿಸಲಾಗಿದೆ (₹)",
    g_category: "ವರ್ಗ",
    g_target_date: "ಗುರಿ ದಿನಾಂಕ (ಐಚ್ಛಿಕ)",
    g_edit_goal: "ಗುರಿಯನ್ನು ತಿದ್ದುಪಡಿ ಮಾಡಿ",
    g_create_goal: "ಹೊಸ ಗುರಿಯನ್ನು ರಚಿಸಿ",
    g_saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    g_save_changes: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    g_create_goal_btn: "ಗುರಿಯನ್ನು ರಚಿಸಿ",
    g_est_completion: "ಅಂದಾಜು ಪೂರ್ಣಗೊಳ್ಳುವಿಕೆ",
    g_month_singular: "ತಿಂಗಳು",
    g_months_plural: "ತಿಂಗಳುಗಳು",
    g_name_required: "ಗುರಿಯ ಹೆಸರು ಅಗತ್ಯವಿದೆ.",
    g_target_gt_0: "ಗುರಿ ಮೊತ್ತವು 0 ಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು.",
    g_contribution_gt_0: "ಮಾಸಿಕ ಕೊಡುಗೆಯು 0 ಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು.",
    g_delete_confirm: "ಈ ಗುರಿಯನ್ನು ಅಳಿಸುವುದೇ? ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.",
    g_toast_deleted: "🗑️ ಗುರಿಯನ್ನು ಅಳಿಸಲಾಗಿದೆ.",
    g_toast_failed_delete: "ಗುರಿಯನ್ನು ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ.",
    g_toast_completed: "🎉 ಗುರಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ!",
    g_toast_failed_complete: "ಪೂರ್ಣಗೊಳಿಸಲು ವಿಫಲವಾಗಿದೆ.",
    o_personal_finance: "ವೈಯಕ್ತಿಕ ಹಣಕಾಸು",
    o_loan_details: "ಸಾಲದ ವಿವರಗಳು",
    o_review_confirm: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ದೃಢೀಕರಿಸಿ",
    o_set_profile: "ನಿಮ್ಮ ಹಣಕಾಸು ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ",
    o_profile_desc: "ಇದಕ್ಕೆ 2 ನಿಮಿಷಗಳು ಬೇಕಾಗುತ್ತವೆ. ನಿಮ್ಮ ಡೇಟಾ ನಿಖರವಾದ ಒತ್ತಡದ ಅಂಕಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    o_income_expenses: "ಆದಾಯ, ವೆಚ್ಚಗಳು ಮತ್ತು ಉಳಿತಾಯ",
    o_existing_loans_opt: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಸಾಲಗಳು (ಐಚ್ಛಿಕ)",
    o_verify_info: "ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    o_monthly_cash_flow: "ನಿಮ್ಮ ಮಾಸಿಕ ನಗದು ಹರಿವಿನ ವಿವರಗಳು",
    o_monthly_income: "ಮಾಸಿಕ ಆದಾಯ *",
    o_monthly_expenses: "ಮಾಸಿಕ ವೆಚ್ಚಗಳು *",
    o_total_savings: "ಒಟ್ಟು ಉಳಿತಾಯ",
    o_emergency_fund: "ತುರ್ತು ನಿಧಿ",
    o_occupation: "ಉದ್ಯೋಗ",
    o_select_occupation_opt: "ಉದ್ಯೋಗವನ್ನು ಆರಿಸಿ (ಐಚ್ಛಿಕ)",
    o_live_preview: "ಲೈವ್ ಮುನ್ನೋಟ",
    o_disposable: "ಬಿಸಾಡಬಹುದಾದ",
    o_existing_loans: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಸಾಲಗಳು",
    o_optional_skip: "ಐಚ್ಛಿಕ — ನಿಮಗೆ ಯಾವುದೇ ಸಾಲಗಳಿಲ್ಲದಿದ್ದರೆ ಬಿಟ್ಟುಬಿಡಿ",
    o_add_loan: "ಸಾಲ ಸೇರಿಸಿ",
    o_no_loans_yet: "ಇನ್ನೂ ಯಾವುದೇ ಸಾಲಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ",
    o_add_first_loan: "+ ಮೊದಲ ಸಾಲ ಸೇರಿಸಿ",
    o_loan_type: "ಸಾಲದ ವಿಧ",
    o_loan_amount_label: "ಸಾಲದ ಮೊತ್ತ (₹)",
    o_interest_rate_label: "ಬಡ್ಡಿ ದರ (%)",
    o_emi_amount_label: "ಇಎಂಐ ಮೊತ್ತ (₹)",
    o_tenure_months_label: "ಅವಧಿ (ತಿಂಗಳುಗಳು)",
    o_estimated_dti: "ಅಂದಾಜು ಡಿಟಿಐ",
    o_everything_looks_good: "ಎಲ್ಲವೂ ಸರಿಯಾಗಿ ಕಾಣುತ್ತಿದೆಯೇ?",
    o_financial_overview: "ಹಣಕಾಸು ಅವಲೋಕನ",
    o_disposable_income: "ಬಿಸಾಡಬಹುದಾದ ಆದಾಯ",
    o_dti_ratio: "ನಿಮ್ಮ ಸಾಲ ಮತ್ತು ಆದಾಯದ ಅನುಪಾತ",
    o_back: "ಹಿಂದೆ",
    o_next: "ಮುಂದೆ",
    o_complete_setup: "ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    o_income_gt_0: "ಮಾಸಿಕ ಆದಾಯವು ₹0 ಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು",
    o_expenses_ge_0: "ವೆಚ್ಚಗಳು 0 ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು",
    o_savings_ge_0: "ಉಳಿತಾಯವು 0 ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚಿರಬೇಕು",
    o_saving_loading: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    o_occupation_salaried: "ವೇತನ ಪಡೆಯುವ ಉದ್ಯೋಗಿ",
    o_occupation_self: "ಸ್ವಯಂ ಉದ್ಯೋಗಿ / ಸ್ವತಂತ್ರ ಉದ್ಯೋಗಿ",
    o_occupation_business: "ವ್ಯಾಪಾರ ಮಾಲೀಕರು",
    o_occupation_govt: "ಸರ್ಕಾರಿ ನೌಕರ",
    o_occupation_student: "ವಿದ್ಯಾರ್ಥಿ",
    o_occupation_retired: "ನಿವೃತ್ತ",
    o_occupation_other: "ಇತರ",
    o_loan_personal: "ವೈಯಕ್ತಿಕ ಸಾಲ",
    o_loan_home: "ಗೃಹ ಸಾಲ",
    o_loan_car: "ಕಾರು ಸಾಲ",
    o_loan_edu: "ಶಿಕ್ಷಣ ಸಾಲ",
    o_loan_biz: "ವ್ಯಾಪಾರ ಸಾಲ",
    o_loan_cc: "ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್",
    o_loan_other: "ಇತರ",
    // New keys
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    new: "ಹೊಸ",
    clearAll: "ಎಲ್ಲ ಅಳಿಸು",
    allCaughtUp: "ಎಲ್ಲವೂ ಪೂರ್ಣ! 🎉",
    askAiAssistant: "ಎಐ ಸಹಾಯ ಕೇಳಿ",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    aiInsightsPanel: "ಎಐ ಒಳನೋಟ",
    currentBalance: "ಪ್ರಸ್ತುತ ಬಾಕಿ",
    neuralEngineActive: "ನರಮಂಡಲದ ಎಂಜಿನ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    aiAdvisorySuggestions: "ಹಣಕಾಸಿನ ನಿಯತಾಂಕಗಳ ಆಧಾರದ ಮೇಲೆ, ವೆಚ್ಚಗಳನ್ನು ಕಡಿಮೆ ಮಾಡಲು ನಾವು ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ.",
    calibrateMicroSavings: "ವಿವಿಧ ಒತ್ತಡದ ಸನ್ನಿವೇಶಗಳನ್ನು ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಲು ಮಾಸಿಕ ಉಳಿತಾಯ ಮಿತಿಗಳನ್ನು ಸಂರಚಿಸಿ.",
    ef_deposit_success: "ಠೇವಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    ef_deposit_failed: "ಠೇವಣಿ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    ef_withdraw_success: "ಹಿಂಪಡೆಯುವಿಕೆ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    ef_withdraw_failed: "ಹಿಂಪಡೆಯುವಿಕೆ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    ef_setup_saved: "ಹಣಕಾಸಿನ ಸೆಟಪ್ ಉಳಿಸಲಾಗಿದೆ!",
    ef_setup_failed: "ಸೆಟಪ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    ef_balance_label: "ಬಾಕಿ",
    ef_mode_gentle: "ಸೌಮ್ಯ ಮೋಡ್",
    ef_mode_moderate: "ಮಧ್ಯಮ ಮೋಡ್",
    ef_mode_aggressive: "ಆಕ್ರಮಣಕಾರಿ ಮೋಡ್",
    ef_per_txn: "/ವಹಿವಾಟು",
    retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    g_cat_other: "🎯 ಇತರ",
    g_cat_vehicle: "🚗 ವಾಹನ",
    g_cat_travel: "✈️ ಪ್ರವಾಸ",
    g_cat_gadget: "💻 ಗ್ಯಾಜೆಟ್",
    g_cat_education: "🎓 ಶಿಕ್ಷಣ",
    g_cat_home: "🏠 ಮನೆ",
    g_cat_health: "❤️ ಆರೋಗ್ಯ",
    g_cat_emergency: "🛡️ ತುರ್ತು" 
  },
  hi: {
    // Navigation
    dashboard: "डैशबोर्ड",
    loans: "मेरे ऋण",
    simulation: "सिम्यूलेशन",
    analysis: "तनाव विश्लेषण",
    fraudCheck: "धोखाधड़ी जांच",
    emergencyFund: "आपातकालीन कोष",
    familyFinance: "पारिवारिक वित्त",
    voiceTrack: "वॉयस ट्रैक",
    myGoals: "मेरे लक्ष्य",
    adminPanel: "व्यवस्थापक पैनल",
    aiInsights: "एआई सुझाव",
    logout: "लॉग आउट",

    // Dashboard
    hello: "नमस्ते",
    welcomeJohn: "स्वागत है, जॉन 👋",
    welcomeUser: "स्वागत है, {name} 👋",
    premiumAccount: "प्रीमियम खाता",
    dashboardDesc: "वेतन कटौती का विश्लेषण करें, मदवार खर्चों को ट्रैक करें, डीटीआई मीट्रिक जांचें, और वास्तविक समय सारांश देखें।",
    configureFinancials: "वित्तीय जानकारी सेट करें",
    injectDemo: "डेमो डेटा डालें",
    monthlyIncome: "मासिक आय",
    expenses: "मासिक खर्च",
    totalEMI: "कुल सक्रिय ईएमआई",
    managedOutflow: "प्रबंधित खर्च",
    debtCommitments: "ऋण प्रतिबद्धताएं",
    financesBreakdown: "वित्तीय विश्लेषण",
    allocationMapping: "आय आवंटन का मानचित्रण",
    activePortfolio: "सक्रिय ऋण",
    portfolioDesc: "सक्रिय ऋण धाराओं का व्यापक ऑडिट",
    manageLoans: "ऋण प्रबंधित करें",
    loanDetails: "ऋण विवरण",
    amount: "राशि",
    rate: "ब्याज दर",
    status: "स्थिति",
    financialHealth: "वित्तीय स्वास्थ्य स्कोर",
    healthStatusExcellent: "उत्कृष्ट स्थिति",
    healthStatusModerate: "सामान्य स्वास्थ्य",
    healthStatusRisk: "जोखिम प्रोफ़ाइल पाया गया",
    healthDesc: "सक्रिय ईएमआई के खिलाफ आपकी बचत मजबूत है।",
    trajectory: "ऋण-तनाव पथ",
    retryConnection: "पुनः प्रयास करें",
    reauthenticate: "पुनः लॉग इन करें",
    failedSync: "डैशबोर्ड सिंक करने में विफल",
    hideSummary: "सारांश छिपाएं",
    inAppSummary: "वित्तीय सारांश",
    confidentialAudit: "गोपनीय ऑडिट",
    deductionsSummary: "कटौती सारांश",
    grossSalaryLabel: "कुल वेतन:",
    pfLabel: "भविष्य निधि (PF):",
    ptLabel: "व्यवसायिक टैक्स:",
    itLabel: "आयकर:",
    netTakeHomeLabel: "शुद्ध वेतन:",
    expenseAllocations: "खर्च आवंटन",
    coreTotal: "कुल खर्च:",
    surplusHeadroom: "बची हुई राशि:",
    dtiRatioLabel: "डीटीआई अनुपात:",
    savingsRateLabel: "बचत दर:",
    advisorRec: "सलाहकार की सिफारिशें",
    savingsCatStatus: "बचत श्रेणी स्थिति:",
    combinedRiskFactor: "संयुक्त जोखिम कारक:",
    dtiTip: "ऋण संकट से बचने के लिए डीटीआई अनुपात 30% से नीचे रखें।",
    howToUseTitle: "स्मार्ट लोन एनालाइजर का उपयोग कैसे करें",
    howToUseDesc: "मंच पर आपका स्वागत है। हमारे वास्तविक गाइड प्रोफाइल, जॉन (28 वर्ष, वेतनभोगी कर्मचारी) का उपयोग करके ऑनबोर्डिंग टूर शुरू करें। वॉकथ्रू देखने के लिए ऊपर क्लिक करें!",
    step1Title: "चरण 1: पंजीकरण/लॉगिन",
    step1Desc: "प्रारंभ करने के लिए साइन अप करें या लॉगिन क्रेडेंशियल दर्ज करें। उदाहरण डेमो प्रोफ़ाइल: ईमेल john@example.com / पासवर्ड John123।",
    step2Title: "चरण 2: वेतन कॉन्फ़िगरेशन",
    step2Desc: "कुल वेतन (₹60,000) दर्ज करें। सिस्टम स्वचालित रूप से 12% पीएफ (₹7,200), व्यावसायिक कर (₹200) और आयकर (₹2,000) काटकर शुद्ध वेतन ₹50,600 दिखाता है।",
    step3Title: "चरण 3: खर्चों की ट्रैकिंग",
    step3Desc: "मासिक खर्च दर्ज करें: किराया (₹15k), भोजन (₹6k), परिवहन (₹2k), बिजली (₹1.5k), इंटरनेट (₹800), बीमा (₹2k), और अन्य खर्च (₹3k) मिलाकर कुल ₹30,300 खर्च होते हैं।",
    step4Title: "चरण 4: शुद्ध बचत",
    step4Desc: "शुद्ध वेतन (₹50,600) ऋण खर्च (₹30,300) घटाने पर ₹20,300 बचते हैं। यह आपकी ऋण सीमा तय करता है।",
    guidedJourneyTitle: "इंटरैक्टिव निर्देशित यात्रा",
    guidedJourneyDesc: "हमने संपूर्ण वॉकथ्रू पेज तैयार किया है। सभी सुविधाओं को देखने के लिए आगे बढ़ें।",
    startWalkthroughBtn: "वॉकथ्रू शुरू करें 🚀",
    leafletLandmarks: "वॉकथ्रू के कदम:",
    leafletLandmarksDesc: "• खाता सेटअप और वेतन • खर्च और बचत ट्रैकिंग • लोन कैलकुलेटर और स्वास्थ्य जांच",
    netSalaryCardTitle: "शुद्ध मासिक वेतन",
    afterDeductions: "पीएफ और टैक्स कटौती के बाद",
    totalMonthlyExpensesTitle: "कुल मासिक खर्च",
    coreOutflowsTracked: "खर्चों का रिकॉर्ड",
    disposableBufferTitle: "बचा हुआ पैसा",
    freeCashSurplus: "शेष राशि",
    monthlyActiveEmisTitle: "सक्रिय मासिक ईएमआई",
    financesAllocProfile: "वित्तीय आवंटन प्रोफ़ाइल",
    financesAllocProfileDesc: "आय, व्यय और ऋण देनदारियों की तुलना।",
    expensesDistTitle: "खर्चों का वितरण",
    expensesDistDesc: "मुख्य व्यय मदों का विश्लेषण।",
    noExpensesConfigured: "अभी तक कोई खर्च कॉन्फ़िगर नहीं किया गया है",
    derivedHealthScore: "बचत क्षमता, खर्च सीमा और ऋण अनुपात के आधार पर गणना की जाती है।",
    healthRatingLabel: "वित्तीय रेटिंग",
    computeLoanAffordability: "ऋण वहन क्षमता जांचें",
    calcMonthlyEmi: "परिकलित मासिक ईएमआई",
    totalInterestPaid: "कुल भुगतान किया गया ब्याज:",
    totalCumRepayment: "कुल संचयी पुनर्भुगतान राशि:",
    affordabilityAnalysisTitle: "ऋण वहन क्षमता विश्लेषण",
    highlyAffordable: "आसानी से वहन योग्य ✅",
    emiDispPercentage: "ईएमआई आपके बचे हुए पैसे का {percent}% है।",
    riskyLeverage: "जोखिम भरा स्तर ⚠️",
    emiRiskyPercentage: "ईएमआई आपके बचे हुए पैसे का {percent}% ले रही है। सावधानी से आगे बढ़ें।",
    notAffordable: "वहन करने योग्य नहीं ❌",
    emiNotAffordablePercentage: "ईएमआई बचे पैसे के 50% ({percent}%) से अधिक है। ऋण न लेने की सलाह दी जाती है।",
    configFinancialProfile: "वित्तीय प्रोफ़ाइल सेट करें",
    specifyIncomeExpenses: "आय के घटकों और खर्चों की मदवार जानकारी दर्ज करें।",
    salaryModuleStructure: "वेतन संरचना",
    grossSalaryInput: "कुल वेतन",
    pfRateInput: "पीएफ दर (%)",
    ptInputLabel: "व्यावसायिक टैक्स (PT)",
    itInputLabel: "आयकर (IT)",
    itemizedExpensesTracking: "व्यय ट्रैकिंग",
    monthlyRentInput: "मासिक किराया",
    foodGroceriesInput: "भोजन और किराना",
    transportInputLabel: "परिवहन",
    electricityInputLabel: "बिजली",
    internetInputLabel: "इंटरनेट / वाईफ़ाई",
    insuranceInputLabel: "बीमा",
    otherExpensesInputLabel: "अन्य खर्च",
    savingFinancials: "सहेजा जा रहा है...",
    saveFinancialsBtn: "वित्तीय जानकारी सहेजें",

    // Goals
    goalsTitle: "वित्तीय लक्ष्य समयरेखा",
    goalsDesc: "बचत लक्ष्यों को परिभाषित करें और खरीद तिथियों का सिम्यूलेशन करें।",
    createGoal: "नया लक्ष्य बनाएं",
    goalIdentifier: "लक्ष्य का नाम",
    targetCost: "लक्ष्य लागत ($)",
    monthlyContribution: "मासिक योगदान",
    addTargetGoal: "लक्ष्य जोड़ें",
    forecastOnline: "समयरेखा भविष्यवाणी",

    // Fraud
    fraudTitle: "AI लेनदेन रक्षक",
    fraudDesc: "लेनदेन को अंतिम रूप देने से पहले जोखिम का विश्लेषण करें।",
    analyzePayment: "भुगतान मानदंडों का विश्लेषण करें",
    settlementAmount: "भुगतान राशि ($)",
    category: "श्रेणी",
    merchant: "प्राप्तकर्ता व्यापारी",
    merchantLoc: "व्यापारी का स्थान",
    analyzeSettlement: "भुगतान का विश्लेषण करें",
    neuralEngine: "AI इंजन सक्रिय है",

    // Family Finance
    familyTitle: "पारिवारिक वित्तीय प्रणाली",
    familyDesc: "साझा वॉलेट, सीमाएं और समूह बचत योजनाओं को प्रबंधित करने के लिए खाते लिंक करें।",
    groupManagement: "समूह प्रबंधन",
    establishGroup: "समूह स्थापित करें",
    establishGroupDesc: "एक सुरक्षित साझा वित्तीय कार्यक्षेत्र आरंभ करें और तुरंत आमंत्रण भेजें।",
    createNewEcosystem: "नया ईकोसिस्टम बनाएं",
    ecosystemConnectionId: "कनेक्शन आईडी",
    provideConnectionIdDesc: "साझा वॉलेट इंडेक्स डाउनलोड करने के लिए पारिवारिक टोकन आईडी प्रदान करें।",
    synchronizeGroup: "समूह सिंक करें",
    synching: "सिंक हो रहा है...",
    inviteCode: "आमंत्रण कोड: ",
    shareCodeWithFamily: "परिवार के साथ कोड साझा करें",
    sharedBalance: "साझा शेष राशि",
    topUp: "+ टॉप अप",
    amountVal: "राशि ($)",
    primaryPool: "प्राथमिक पूल",
    activeWallet: "सक्रिय वॉलेट",
    ecosystemMembers: "समूह सदस्य",
    connected: "कनेक्टेड",
    recentTransactions: "हालिया पारिवारिक पूल लेनदेन",
    liveLedger: "लाइव लेज़र",
    member: "सदस्य",
    reason: "कारण",
    date: "तारीख",
    noTransactions: "कोई लेनदेन दर्ज नहीं है।",
    addMember: "परिवार का सदस्य जोड़ें",
    inviteMemberDesc: "उनके ईमेल का उपयोग करके सीमाएं और खर्चे समन्वित करने के लिए आमंत्रित करें।",
    emailAddress: "ईमेल पता",
    nickname: "उपनाम",
    role: "भूमिका",
    monthlyLimit: "मासिक सीमा ($)",
    parent: "अभिभावक",
    child: "बच्चा",
    elder: "बुजुर्ग",
    sendingInvite: "आमंत्रित किया जा रहा है...",
    inviteSuccess: "परिवार का सदस्य सफलतापूर्वक जोड़ा गया!",

    // Emergency Fund
    fundTitle: "आपातकालीन साझा वॉलेट और फंड",
    fundDesc: "आपातकालीन आवश्यकताओं के लिए धन सुरक्षित रखें। मासिक योगदान देकर ऋण तनाव से बचें।",
    fundBalance: "फंड शेष राशि",
    monthsOfRunway: "सुरक्षित महीनों की संख्या",
    runwayDesc: "वर्तमान शेष राशि और खर्चों के आधार पर सुरक्षित रहने के अनुमानित महीने।",
    fundGoal: "फंड का लक्ष्य",
    monthlyContributionGraph: "मासिक योगदान प्रगति",
    contribute: "फंड में योगदान करें",
    withdraw: "आपातकालीन निकासी",

    // Simulation
    simTitle: "ब्याज दर सिम्यूलेटर",
    simDesc: "मूलधन में बदलाव, ब्याज दरों या अतिरिक्त पूर्व-भुगतानों का विश्लेषण करें।",
    loanDetailsForm: "ऋण मानदंड",
    simulateButton: "सिम्यूलेशन चलाएं",
    simResults: "सिम्यूलेशन परिणाम और मेट्रिक्स",

    // Stress Analysis
    stressTitle: "ऋण तनाव और भेद्यता ऑडिट",
    stressDesc: "विभिन्न वित्तीय झटकों के तहत आपके नकद प्रवाह के जोखिम का विश्लेषण करें।",
    runStressCheck: "जोखिम स्कैन चलाएं",

    // Voice Tracker
    voiceTitle: "आवाज आधारित ऋण सहायक",
    voiceDesc: "प्राकृतिक आवाज आदेशों के साथ अपने ऋण का प्रबंधन करें।",
    speakCommand: "बोलने के लिए टैप करें",
    listening: "सुन रहा हूँ...",

    // General UI
    save: "सहेजें",
    cancel: "रद्द करें",
    loadingVal: "लोड हो रहा है...",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    inviteCodeRequired: "सिंक करने के लिए ग्रुप आईडी आवश्यक है",

    // Loans
    manageLoansLocally: "अपने ऋण स्थानीय रूप से प्रबंधित करें। सिम्यूलेशन बैकएंड का उपयोग करता है।",
    addNewLoan: "नया ऋण जोड़ें",
    loanType: "ऋण का प्रकार",
    loanTypePlaceholder: "जैसे, गृह ऋण",
    amountPlaceholder: "150000",
    interestPlaceholder: "3.5",
    durationPlaceholder: "240",
    adding: "जोड़ा जा रहा है...",
    addLoanButton: "ऋण जोड़ें",
    yourLoans: "आपके ऋण",
    noLoans: "अभी तक कोई ऋण नहीं जोड़ा गया है।",
    amountLabel: "राशि",
    interestLabel: "ब्याज",
    durationLabel: "अवधि",
    statusLabel: "स्थिति",

    // Simulation Additional
    simSandbox: "इंटरैक्टिव सैंडबॉक्स",
    simMainTitle: "वित्तीय परिदृश्य सिम्यूलेटर",
    simDescExtended: "ब्याज बचत को अनलॉक करने के लिए अतिरिक्त भुगतानों और पुनर्वित्त दरों को सिम्युलेट करें।",
    scenarioParams: "परिदृश्य पैरामीटर",
    scenarioDesc: "इनपुट्स को समायोजित करें या टेस्ट करने के लिए स्लाइडर्स का उपयोग करें।",
    loanPrincipal: "ऋण मूलधन ($)",
    tenureHorizon: "अवधि सीमा (महीने)",
    tenure1Year: "1 वर्ष (12 महीने)",
    tenure15Years: "15 वर्ष (180 महीने)",
    tenure30Years: "30 वर्ष (360 महीने)",
    payoffBoosters: "Payoff बूस्टर विकल्प",
    extraMonthlyPayoff: "अतिरिक्त मासिक भुगतान ($)",
    oneTimePrepayment: "एकमुश्त भुगतान ($)",
    simCompounding: "पुनर्भुगतान सिम्युलेट किया जा रहा है...",
    runSandbox: "सैंडबॉक्स सिम्यूलेशन चलाएं",
    calcException: "गणना त्रुटि",
    waitingScenario: "परिदृश्य की प्रतीक्षा की जा रही है",
    waitingScenarioDesc: "अपने सिमुलेशन मेट्रिक्स का चयन करें और 'सिम्यूलेशन चलाएं' पर क्लिक करें।",
    interestSavings: "ब्याज बचत",
    interestSavingsDesc: "देखें कि समय से पहले भुगतान करने से कितना ब्याज बचता है।",
    timelineShortening: "समयसीमा में कमी",
    timelineShorteningDesc: "मासिक बजट समायोजित करें और नए ऋण-मुक्त दिन को ट्रैक करें।",
    compoundingBenefit: "चक्रवृद्धि ब्याज लाभ",
    repaymentSummary: "पुनर्भुगतान सारांश",
    highOptimization: "उच्च अनुकूलन",
    projectedInterestSaved: "अनुमानित ब्याज बचत",
    interestSavedDesc: "यह वह पैसा है जो ब्याज में जाने के बजाय आपके पास बचेगा।",
    newMonthlyEmi: "नई मासिक ईएमआई",
    remainingHorizon: "शेष भुगतान अवधि",
    optimizedDate: "अनुकूलित ऋण-मुक्त तिथि",
    payoffComparison: "भुगतान अवधि तुलना",
    originalHorizon: "मूल अवधि",
    optimizedHorizon: "अनुकूलित अवधि",
    quicker: "तेजी से!",
    aiScenarioCounsel: "एआई परिदृश्य सलाह",
    synthesizingData: "डेटा का विश्लेषण किया जा रहा है...",
    retriggerAI: "एआई विश्लेषण पुनः चलाएं",

    // Stress Analysis Additional
    coreRiskDiagnostic: "मुख्य जोखिम निदान",
    debtStressAnalysisTitle: "ऋण तनाव विश्लेषण",
    debtStressDescExtended: "समझें कि आपके मासिक ऋण भुगतान आपके नकद प्रवाह पर कितना दबाव डालते हैं।",
    incomeMinusExpenses: "आय ऋण निश्चित व्यय",
    activeLoanPayments: "सभी सक्रिय ऋण भुगतानों का योग",
    disposableCashflow: "बचा हुआ नकद प्रवाह",
    totalMonthlyEmi: "कुल मासिक ईएमआई",
    combinedStressScore: "संयुक्त तनाव स्कोर",
    debtToDisposableRatio: "ऋण से आय अनुपात",
    historicalTrend: "ऐतिहासिक जोखिम रुझान",
    timelineTrackStress: "आपके ऋण तनाव स्कोर का ऐतिहासिक रुझान।",
    stressContribution: "ऋण वार तनाव योगदान",
    isolatedImpactScore: "प्रत्येक सक्रिय ऋण का आपके नकद प्रवाह पर व्यक्तिगत तनाव स्कोर।",
    activeObligation: "सक्रिय दायित्व",
    stressRatio: "तनाव अनुपात",
    noLoansDetected: "कोई ऋण नहीं पाया गया",
    noLoansDetectedDesc: "तनाव ऑडिट की समीक्षा करने के लिए ऋण बही में ऋण देनदारियां जोड़ें।",
    primaryStressDriver: "मुख्य तनाव चालक",
    contributesLargest: "नकद प्रवाह पर सबसे बड़ा दबाव बिंदु बनता है",
    ratioText: "व्यक्तिगत अनुपात।",
    debtDisposableRatioText: "ऋण से बची हुई नकद राशि का अनुपात:",
    consumeDisposable: "आपकी ईएमआई आपके बजट का हिस्सा लेती हैं",
    safeCashflowRunway: "सुरक्षित नकद प्रवाह अवधि:",
    preserveMonthlyNet: "आप मासिक शुद्ध नकद राशि बचाते हैं",
    discretionarySavings: "बचत और विवेकाधीन गतिविधियों के लिए।",
    cashflowAlert: "नकद प्रवाह चेतावनी",
    stressExceedsWarning: "आपका ऋण तनाव अनुपात अनुशंसित 35% सुरक्षित सीमा से अधिक है। बजट घाटे को रोकने के लिए ऋण पुनर्वित्त की सलाह दी जाती है।",

    // Walkthrough content
    w_welcome_title: "👋 स्वागत है जॉन!",
    w_welcome_subtitle: "अपने गाइड साथी से मिलें",
    w_welcome_desc: "नमस्ते, मैं जॉन हूँ। मैं आपको दिखाता हूँ कि स्मार्ट लोन विश्लेषक मुझे मेरे पैसे का प्रबंधन करने में कैसे मदद करता है।",
    w_welcome_label: "प्रोफ़ाइल सारांश",
    w_welcome_body: "आयु: 28 वर्ष \nपेशा: वेतनभोगी कर्मचारी \nलक्ष्य: पैसे बचाएं, ऋण संकट से बचें और नई बाइक की योजना बनाएं।",
    w_welcome_footer: "🎯 यात्रा का उद्देश्य: नकद भंडार स्वस्थ रखना",

    w_account_title: "👤 खाता बनाएं",
    w_account_subtitle: "वित्तीय सुरक्षा की दिशा में पहला कदम",
    w_account_desc: "पहले अपना खाता बनाएं ताकि ऐप जान सके कि आप कौन हैं।",
    w_account_label: "पंजीकरण",
    w_account_footer: "सत्यापित डेमो प्रोफ़ाइल विवरण",

    w_salary_title: "💰 वेतन अनुभाग",
    w_salary_subtitle: "कुल वेतन बनाम शुद्ध वेतन",
    w_salary_desc: "जॉन वेतन अनुभाग में पहुंचता है 💰। मैं सबसे पहले अपना मासिक वेतन जोड़ता हूँ।",
    w_salary_label: "वेतन विश्लेषण",

    w_expense_title: "🏠 खर्च अनुभाग",
    w_expense_subtitle: "ट्रैक करें कि आपका पैसा कहाँ जाता है",
    w_expense_desc: "जॉन खर्च अनुभाग 🏠 में पहुंचता है। मैं हर महीने ट्रैक करता हूँ कि मेरा पैसा कहाँ जाता है।",
    w_expense_label: "व्यय श्रेणियां",

    w_savings_title: "📊 शुद्ध बचत",
    w_savings_subtitle: "बचा हुआ नकद प्रवाह",
    w_savings_desc: "जॉन बचत अनुभाग 📊 में पहुंचता है। यह मुझे बताता है कि मैं कितना पैसा बचा सकता हूँ।",
    w_savings_label: "बचत बफर",

    w_loan_title: "🏦 ऋण कैलकुलेटर",
    w_loan_subtitle: "ईएमआई और वहन क्षमता विश्लेषण",
    w_loan_desc: "जॉन ऋण कैलकुलेटर 🏦 में पहुंचता है। मैं ऋण लेने से पहले जाँच करता हूँ कि क्या मैं इसे वहन कर सकता हूँ।",
    w_loan_label: "बाइक ऋण सिमुलेशन",

    w_stress_title: "⚠️ ऋण तनाव विश्लेषण",
    w_stress_subtitle: "वेतन का कितना हिस्सा ऋण में जाता है",
    w_stress_desc: "जॉन ऋण तनाव विश्लेषण ⚠️ में पहुंचता है। ऐप मुझे बताता है कि मेरे ऋण सुरक्षित हैं या जोखिम भरे।",
    w_stress_label: "तनाव सूचक",

    w_fund_title: "🛟 आपातकालीन फंड",
    w_fund_subtitle: "अत्यावश्यकताओं के लिए बचत",
    w_fund_desc: "जॉन आपातकालीन फंड 🛟 में पहुंचता है। मैं आपातकालीन स्थितियों के लिए पैसे तैयार रखता हूँ।",
    w_fund_label: "सुरक्षा कोष",

    w_goals_title: "🎯 वित्तीय लक्ष्य",
    w_goals_subtitle: "भविष्य के सपनों की योजना",
    w_goals_desc: "जॉन वित्तीय लक्ष्य 🎯 में पहुंचता है। मैं अपने भविष्य के लक्ष्यों की योजना बनाता हूँ।",
    w_goals_label: "भविष्य के लक्ष्य",

    w_ai_title: "🤖 एआई सहायक",
    w_ai_subtitle: "आपका वित्तीय रोबोट मित्र",
    w_ai_desc: "जॉन एआई सहायक 🤖 से मिलता है। मैं वित्तीय प्रश्न पूछ सकता हूँ और मार्गदर्शन प्राप्त कर सकता हूँ।",
    w_ai_label: "एआई सुझाव",

    w_dashboard_title: "📈 डैशबोर्ड सारांश",
    w_dashboard_subtitle: "समग्र वित्तीय स्वास्थ्य का अवलोकन",
    w_dashboard_desc: "जॉन डैशबोर्ड 📈 पर पहुंचता है। अब मैं अपना पूरा वित्तीय स्वास्थ्य देख सकता हूँ।",
    w_dashboard_label: "स्वास्थ्य स्थिति",

    w_prev: "पिछला",
    w_next: "अगला कदम",
    w_finish: "डैशबोर्ड में प्रवेश करें",
    w_skip: "दौरा छोड़ें",
    // New keys
    notifications: "सूचनाएं",
    new: "नया",
    clearAll: "सभी साफ करें",
    allCaughtUp: "सब समाप्त! 🎉",
    askAiAssistant: "एआई सहायक से पूछें",
    selectLanguage: "भाषा चुनें",
    aiInsightsPanel: "एआई अंतर्दृष्टि पैनल",
    currentBalance: "वर्तमान शेष",
    neuralEngineActive: "तंत्रिका इंजन सक्रिय",
    aiAdvisorySuggestions: "वित्तीय मापदंडों के आधार पर, हम विवेकाधीन खर्चों को अनुकूलित करने की सलाह देते हैं।",
    calibrateMicroSavings: "विभिन्न तनाव परिदृश्यों का अनुकरण करने के लिए बचत सीमाएँ सेट करें।",
    ef_deposit_success: "जमा सफल रहा!",
    ef_deposit_failed: "जमा विफल रहा। पुनः प्रयास करें।",
    ef_withdraw_success: "निकासी सफल रही!",
    ef_withdraw_failed: "निकासी विफल रही। पुनः प्रयास करें।",
    ef_setup_saved: "वित्तीय सेटअप सहेज लिया गया!",
    ef_setup_failed: "सेटअप विफल रहा। पुनः प्रयास करें।",
    ef_balance_label: "शेष",
    ef_mode_gentle: "सामान्य मोड",
    ef_mode_moderate: "मध्यम मोड",
    ef_mode_aggressive: "आक्रामक मोड",
    ef_per_txn: "/लेनदेन",
    retry: "पुनः प्रयास करें",
    g_cat_other: "🎯 अन्य",
    g_cat_vehicle: "🚗 वाहन",
    g_cat_travel: "✈️ यात्रा",
    g_cat_gadget: "💻 गैजेट",
    g_cat_education: "🎓 शिक्षा",
    g_cat_home: "🏠 घर",
    g_cat_health: "❤️ स्वास्थ्य",
    g_cat_emergency: "🛡️ आपातकालीन"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('language') || 'en';
    return translations[saved] ? saved : 'en';
  });

  const setLanguage = (lang) => {
    if (!translations[lang]) return;
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  useEffect(() => {
    const handler = (e) => {
      if (e?.detail && translations[e.detail]) {
        setLanguageState(e.detail);
      }
    };
    window.addEventListener('language-change', handler);
    return () => window.removeEventListener('language-change', handler);
  }, []);

  const toggleLanguage = () => {
    setLanguageState((prev) => {
      const next = prev === 'en' ? 'hi' : prev === 'hi' ? 'kn' : 'en';
      localStorage.setItem('language', next);
      return next;
    });
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
